### ISSUE TITLE
[Bug]: Duplicate record 11

### ISSUE THREAD

**Issue by Delitel-WEB** [spartacus04/jext-reborn#106]
### Describe the bug

When creating a record, it is given an id like plate 11, which is why the sound from two records can be played at the same time

When creating on: https://spartacus04.github.io/jext-reborn/

### Steps to reproduce

It doesn't work every time, but if you insert and pull out the record a few times, you can hear the record playing in the background 11

### Expected behaviour

Two records should not be played in one

### Server Version

1.19.2

### Server Type

Paper

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by spartacus04** [comment]
Hi, I was able to fix the bug in [7841ee3](https://github.com/spartacus04/jext-reborn/commit/7841ee38a32d3e2f53b51c5dd94f7907aed5f68a), it should be implemented in the next update

**Comment by Delitel-WEB** [comment]
okay thanks
