### ISSUE TITLE
[Bug]: music discs dissapearing

### ISSUE THREAD

**Issue by XDeadlyK1llerX** [spartacus04/jext-reborn#109]
### Describe the bug

whenever i play a song it just dissappears randomly. im not sure if its only when i tp away and then come back but it happens everytime. im on 1.19.4 and have the latest version of ProtocolLib

### Steps to reproduce

1. Play music disc.
2. teleport away
3. teleport back
4. music disc is gone

### Expected behaviour

music discs don't randomly dissapear

### Server Version

1.19.4

### Server Type

Paper

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by nuttapillar** [comment]
I'm also getting this, in Purpur 1.19.4. After they disappeared, I gave myself bunch of custom discs again, and put them in 3 different chests that are over jukeboxes. they were all fine for a while, but now 2 have lost their discs, but one remains fine, with all discs in tact

**Comment by nuttapillar** [comment]
> > I'm also getting this, in Purpur 1.19.4. After they disappeared, I gave myself bunch of custom discs again, and put them in 3 different chests that are over jukeboxes. they were all fine for a while, but now 2 have lost their discs, but one remains fine, with all discs in tact
> 
> I figured out the issue. You have to temporarily disable Juke Looper until a new version is released. The plugin isn't working for 1.19.4 yet

Thanks, I'll try that. IDK why I still even had it installed. I don't need it since 1.19.4 anyway, since it has the same functionality in Vanilla now.
