### ISSUE TITLE
[Bug]: 11 plays same time as disc

### ISSUE THREAD

**Issue by mozzz14** [spartacus04/jext-reborn#117]
### Describe the bug

when putting a disc in music disc 11 plays at the same time 

### Steps to reproduce

get custom disc
put in
bug

### Expected behaviour

not play 11

### Server Version

1.19.4

### Server Type

Paper

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by spartacus04** [comment]
Hi, I was able to fix the bug in [7841ee3](https://github.com/spartacus04/jext-reborn/commit/7841ee38a32d3e2f53b51c5dd94f7907aed5f68a), it should be implemented in the next update
