### ISSUE TITLE
[Bug]: plugin not being loaded

### ISSUE THREAD

**Issue by Cre3perDev** [spartacus04/jext-reborn#125]
### Describe the bug

In 1.19.4 when i do /pl the plugin is red and when i try to run any command it doesnt work

### Steps to reproduce

1.Lanched Minecraft 1.19.4 2. did /pl 3. it was red 4. Run any command for that plugin

### Expected behaviour

In 1.19.4 when i do /pl the plugin is red and when i try to run any command it doesnt work

### Server Version

1.19.4

### Server Type

Paper

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by spartacus04** [comment]
Hi, was the disc.json file loaded correctly? Could you please attach a server log?
