### ISSUE TITLE
[Bug]: Discs Only Play 11

### ISSUE THREAD

**Issue by ITSAME420** [spartacus04/jext-reborn#135]
### Describe the bug

you try to play a disc and it just plays 11

### Steps to reproduce

1. Get the disc with the command
2. Play the disc

### Expected behaviour

It should just play the song If Im correct

### Server Version

1.20.1

### Server Type

Spigot

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by ITSAME420** [comment]
> Hi, thanks for the bug report. Did the plugin load correctly? Could you send me the discs.json and resource pack file?
[https://www.dropbox.com/scl/fi/1mwbcafe4fshq2q4evh55/open-me-3.zip?rlkey=asn1cekb27kwgew0006wxj6jx&dl=0](url)

**Comment by ITSAME420** [comment]
It Loaded properly because I could play the music using the /playmusic command, but it won't let me share my disc.json or the resource pack files.

**Comment by spartacus04** [comment]
Ok, perhaps the disc item is bug. Can you put the disc in a chest, and then do a `/data get block <x of chest> <y of chest> <z of chest>` and send the output here? Since minecraft doesn't allow copying from chat you can copy the output from the server logs

**Comment by spartacus04** [comment]
Also which command did you use to get the disc? /discgive or /disc?

**Comment by ITSAME420** [comment]
i used both commands, my server doesn't show output through the logs

**Comment by spartacus04** [comment]
Perhaps you could screenshot the output of the command then? Sorry if I'm a bit insistent but the two commands are both working on my end so without logs, the discs.json/rp or the command I can't really help you.

**Comment by ITSAME420** [comment]
![image](https://github.com/spartacus04/jext-reborn/assets/139574838/bd428ff1-f945-4d47-bac0-e7a138fe8c75)

**Comment by spartacus04** [comment]
Ok, the disc looks fine so it's not really a problem of the commands. Are you using the jukebox gui?

**Comment by ITSAME420** [comment]
Thats set in the config correct?

**Comment by spartacus04** [comment]
yeah, the one in the config. Is it set to "vanilla" or "gui"?

**Comment by ITSAME420** [comment]
gui

**Comment by spartacus04** [comment]
Does the disc play the 11 track when clicking on the jukebox with a disc or when left-clicking the custom disc on the gui?

**Comment by ITSAME420** [comment]
when left clicking in the gui, But I fixed it, it was set to vanilla instead of gui, must not have saved when I set it

**Comment by spartacus04** [comment]
Oh ok, I'm happy you solved it. I'll close this issue now.

**Comment by ITSAME420** [comment]
thanks for the help
