### ISSUE TITLE
[Bug]: Music not stopping after disc removal

### ISSUE THREAD

**Issue by DaddyRobLIVE** [spartacus04/jext-reborn#136]
### Describe the bug

Music not stopping after disc removal

### Steps to reproduce

1. Insert custom disc into jukebox
2. Remove custom disc
3. Music keeps playing

### Expected behaviour

Music should stop playing after removing music disc

### Server Version

1.20.1

### Server Type

Paper

### Discs.json

```json
[
  {
    "title": "Cupid (Twin Version)",
    "author": "Fifty Fifty",
    "duration": 179,
    "disc-namespace": "music_disc.cupidtwinversionfiftyfiftyzero",
    "model-data": 1,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "Tahanan",
    "author": "Adie",
    "duration": 306,
    "disc-namespace": "music_disc.tahananadieone",
    "model-data": 2,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "Uhaw",
    "author": "Dilaw",
    "duration": 240,
    "disc-namespace": "music_disc.uhawdilawtwo",
    "model-data": 3,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "Bones",
    "author": "Imagine Dragons",
    "duration": 166,
    "disc-namespace": "music_disc.bonesimaginedragonszero",
    "model-data": 4,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "Pasilyo",
    "author": "Sunkissed Lola",
    "duration": 274,
    "disc-namespace": "music_disc.pasilyosunkissedlolaone",
    "model-data": 5,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "BMW",
    "author": "Because",
    "duration": 167,
    "disc-namespace": "music_disc.bmwbecausetwo",
    "model-data": 6,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "Ikaw Lang",
    "author": "Nobita",
    "duration": 264,
    "disc-namespace": "music_disc.ikawlangnobitazero",
    "model-data": 7,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "Pagsamo",
    "author": "Arthur Nery",
    "duration": 291,
    "disc-namespace": "music_disc.pagsamoarthurneryone",
    "model-data": 8,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "Nadarang",
    "author": "Shanti Dope",
    "duration": 229,
    "disc-namespace": "music_disc.nadarangshantidopetwo",
    "model-data": 9,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "Dayang Dayang",
    "author": "Sweetnotes",
    "duration": 248,
    "disc-namespace": "music_disc.dayangdayangsweetnoteszero",
    "model-data": 10,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "LDR",
    "author": "Shoti",
    "duration": 212,
    "disc-namespace": "music_disc.ldrshotione",
    "model-data": 11,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  }
]
```

### Resource pack

https://cdn.discordapp.com/attachments/1047763482453487656/1129412728403005512/Bayanihan_Pack_v1.15.8.zip

### Jukebox Behaviour

Vanilla

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by DaddyRobLIVE** [comment]
Additional, only opped players can play the disc. Normal players will only trigger the Disc 11

**Comment by spartacus04** [comment]
Hi, thanks for the bug report, I just fixed this in [0b6c818](https://github.com/spartacus04/jext-reborn/commit/0b6c818d108f6fd4e15ac6207e64665338337dc8) and I'll now release an update with the bug fix

**Comment by DaddyRobLIVE** [comment]
Music still keeps going on even after removing the disc on the jukebox. Will check if this is being caused by a different plugin.

**Comment by spartacus04** [comment]
What other plugin do you have installed? The only plugins that jext interacts with are worldguard and griefprevention. Also of you use Jukelooper the integration only works in <=1.19.3 since It wasn't updated since

**Comment by DaddyRobLIVE** [comment]
I have music box and procosmetics I wonder if those interferes with your
plugin. I'm about to test your plugin without any other plugins to confirm.

**Comment by spartacus04** [comment]
Yeah I just tested it out with those plugins and musicbox was the problem. For now I'll mark musicbox as an unsupported plugin but I'll be sure to work with it's author to fix the bug.

**Comment by DaddyRobLIVE** [comment]
> Yeah I just tested it out with those plugins and musicbox was the problem. For now I'll mark musicbox as an unsupported plugin but I'll be sure to work with it's author to fix the bug.

Ok thank you, I'll remove that plugin for now while waiting for the fix.

**Comment by spartacus04** [comment]
Ok, I just made a change in the latest commit that should make the music stop even when musicbox is installed, however i didn't test if musicbox features were working correctly as I never worked with the plugin, I'll release an update now with the fix

**Comment by DaddyRobLIVE** [comment]
Sure, I'll try that. Thank you so much!
