### ISSUE TITLE
[Bug]: Cant hear music when played in jukebox

### ISSUE THREAD

**Issue by vreeno** [spartacus04/jext-reborn#139]
### Describe the bug

I found the disc in survivel and every thing works but it doesnt play sound when in juke box

### Steps to reproduce

sd

### Expected behaviour

ds

### Logs

sd

### Server Version

1.20.1

### Server Type

Spigot

### Discs.json

```json
sdsd
```

### Resource pack

sd

### Jukebox Behaviour

Vanilla

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by vreeno** [comment]
[
  {
    "title": "Leave Her",
    "author": "LUCKI",
    "duration": 139,
    "disc-namespace": "music_disc.leaveherluckizero",
    "model-data": 1,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/desert_pyramid",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/nether_bridge",
      "chests/jungle_temple",
      "chests/igloo_chest",
      "chests/end_city_treasure",
      "chests/pillager_outpost",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/abandoned_mineshaft",
      "chests/woodland_mansion"
    ],
    "fragment-loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/desert_pyramid",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/nether_bridge",
      "chests/jungle_temple",
      "chests/igloo_chest",
      "chests/end_city_treasure",
      "chests/pillager_outpost",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/abandoned_mineshaft",
      "chests/woodland_mansion"
    ]
  },
  {
    "title": "Y NOT",
    "author": "LUCKI",
    "duration": 151,
    "disc-namespace": "music_disc.ynotluckione",
    "model-data": 2,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/desert_pyramid",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/nether_bridge",
      "chests/jungle_temple",
      "chests/igloo_chest",
      "chests/pillager_outpost",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/abandoned_mineshaft",
      "chests/woodland_mansion"
    ],
    "fragment-loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/desert_pyramid",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/nether_bridge",
      "chests/jungle_temple",
      "chests/igloo_chest",
      "chests/end_city_treasure",
      "chests/pillager_outpost",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/woodland_mansion",
      "chests/abandoned_mineshaft",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house"
    ]
  },
  {
    "title": "Mabu",
    "author": "LUCKI",
    "duration": 156,
    "disc-namespace": "music_disc.mabuluckitwo",
    "model-data": 3,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/desert_pyramid",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/nether_bridge",
      "chests/jungle_temple",
      "chests/igloo_chest",
      "chests/end_city_treasure",
      "chests/pillager_outpost",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/abandoned_mineshaft",
      "chests/woodland_mansion"
    ],
    "fragment-loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/end_city_treasure",
      "chests/igloo_chest",
      "chests/jungle_temple",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/desert_pyramid",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/nether_bridge",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/pillager_outpost",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/abandoned_mineshaft",
      "chests/woodland_mansion"
    ]
  },
  {
    "title": "GoStyle 2023 Freestyle",
    "author": "JACE!",
    "duration": 93,
    "disc-namespace": "music_disc.gostyletwozerotwothreefreestylejacethree",
    "model-data": 4,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/desert_pyramid",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/nether_bridge",
      "chests/jungle_temple",
      "chests/igloo_chest",
      "chests/end_city_treasure",
      "chests/pillager_outpost",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/abandoned_mineshaft",
      "chests/woodland_mansion",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house"
    ],
    "fragment-loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/end_city_treasure",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/jungle_temple",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/igloo_chest",
      "chests/desert_pyramid",
      "chests/nether_bridge",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/pillager_outpost",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/woodland_mansion",
      "chests/abandoned_mineshaft"
    ]
  },
  {
    "title": "Sky",
    "author": "Playboi Carti",
    "duration": 193,
    "disc-namespace": "music_disc.skyplayboicartifour",
    "model-data": 5,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/desert_pyramid",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/nether_bridge",
      "chests/jungle_temple",
      "chests/end_city_treasure",
      "chests/igloo_chest",
      "chests/pillager_outpost",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/woodland_mansion",
      "chests/abandoned_mineshaft",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house"
    ],
    "fragment-loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/end_city_treasure",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/desert_pyramid",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/nether_bridge",
      "chests/jungle_temple",
      "chests/igloo_chest",
      "chests/woodland_mansion",
      "chests/abandoned_mineshaft",
      "chests/pillager_outpost",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house"
    ]
  },
  {
    "title": "Magnolia",
    "author": "Playboi Carti",
    "duration": 205,
    "disc-namespace": "music_disc.magnoliaplayboicartifive",
    "model-data": 6,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/end_city_treasure",
      "chests/desert_pyramid",
      "chests/nether_bridge",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/jungle_temple",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/igloo_chest",
      "chests/pillager_outpost",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/abandoned_mineshaft",
      "chests/woodland_mansion"
    ],
    "fragment-loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/end_city_treasure",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/igloo_chest",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/jungle_temple",
      "chests/desert_pyramid",
      "chests/nether_bridge",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/pillager_outpost",
      "chests/woodland_mansion",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/abandoned_mineshaft",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small"
    ]
  },
  {
    "title": "16",
    "author": "Baby Keem",
    "duration": 158,
    "disc-namespace": "music_disc.onesixbabykeemsix",
    "model-data": 7,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "chests/end_city_treasure",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/igloo_chest",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "archaeology/trail_ruins_rare",
      "chests/desert_pyramid",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/nether_bridge",
      "chests/jungle_temple",
      "chests/pillager_outpost",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/woodland_mansion",
      "chests/abandoned_mineshaft"
    ],
    "fragment-loot-tables": [
      "chests/end_city_treasure",
      "archaeology/trail_ruins_rare",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/igloo_chest",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/jungle_temple",
      "chests/desert_pyramid",
      "chests/nether_bridge",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/pillager_outpost",
      "chests/woodland_mansion",
      "chests/abandoned_mineshaft"
    ]
  },
  {
    "title": "Honest",
    "author": "Baby Keem",
    "duration": 230,
    "disc-namespace": "music_disc.honestbabykeemseven",
    "model-data": 8,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "chests/end_city_treasure",
      "archaeology/trail_ruins_rare",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/igloo_chest",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/jungle_temple",
      "chests/desert_pyramid",
      "chests/nether_bridge",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/pillager_outpost",
      "chests/woodland_mansion",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/abandoned_mineshaft",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small"
    ],
    "fragment-loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/end_city_treasure",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/igloo_chest",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/jungle_temple",
      "chests/desert_pyramid",
      "chests/nether_bridge",
      "chests/ruined_portal",
      "chests/pillager_outpost",
      "chests/woodland_mansion",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/abandoned_mineshaft",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/simple_dungeon"
    ]
  },
  {
    "title": "If Looks Could Kill",
    "author": "Destroy Lonely",
    "duration": 195,
    "disc-namespace": "music_disc.iflookscouldkilldestroylonelyeight",
    "model-data": 9,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/end_city_treasure",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/jungle_temple",
      "chests/desert_pyramid",
      "chests/nether_bridge",
      "chests/simple_dungeon",
      "chests/igloo_chest",
      "chests/ruined_portal",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/pillager_outpost",
      "chests/woodland_mansion",
      "chests/abandoned_mineshaft"
    ],
    "fragment-loot-tables": [
      "chests/end_city_treasure",
      "archaeology/trail_ruins_rare",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/desert_pyramid",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/nether_bridge",
      "chests/jungle_temple",
      "chests/igloo_chest",
      "chests/pillager_outpost",
      "chests/woodland_mansion",
      "chests/abandoned_mineshaft",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house"
    ]
  },
  {
    "title": "NEVEREVER",
    "author": "Destroy Lonely",
    "duration": 145,
    "disc-namespace": "music_disc.nevereverdestroylonelynine",
    "model-data": 10,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/desert_pyramid",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/nether_bridge",
      "chests/jungle_temple",
      "chests/igloo_chest",
      "chests/end_city_treasure",
      "chests/pillager_outpost",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/abandoned_mineshaft",
      "chests/woodland_mansion"
    ],
    "fragment-loot-tables": [
      "archaeology/trail_ruins_rare",
      "chests/end_city_treasure",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/igloo_chest",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/jungle_temple",
      "chests/desert_pyramid",
      "chests/nether_bridge",
      "chests/simple_dungeon",
      "chests/ruined_portal",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/pillager_outpost",
      "chests/woodland_mansion",
      "chests/abandoned_mineshaft"
    ]
  }
]

**Comment by spartacus04** [comment]
Hi, thanks for the bug report.
Did the plugin output any error? Did you apply the resource pack?

Also next time please fill out the form correctly.

**Comment by vreeno** [comment]
im pretty sure i have discs.json and your_pack_name in the jukeboxextendedreborn plugin fold am i suppose to put anything anywhere else?

**Comment by vreeno** [comment]
it works now i didnt have it as server pack

**Comment by spartacus04** [comment]
Glad to hear you solved it
