### ISSUE TITLE
[Bug]: An internal error occurred while attempting to perform this command.

### ISSUE THREAD

**Issue by therealjar** [spartacus04/jext-reborn#141]
### Describe the bug

Plugin doesn't appear as activated, but the command of /discgive is recognized [but gives the error message in the title] , and /discs isnt. 

### Steps to reproduce

I have the plugin installed, with the latest dev build of ProtocolLib on my 1.20 server. discs.json and config.json are both in the JukeboxExtendedReborn folder. I don't have the Jext.jar file that the readme tells me to have, I dont know what that is. The plugin .jar file is in the plugins directory separated from the JukeboxExtendedReborn folder. I have the resource pack completed.

### Expected behaviour

I don't know what I expected, I suck at plugins, so this could be something simple that I'm doing wrong. But I just hoped that it would work once i put the json file in the directory. I think that our discs.json file isn't set up properly, but I wasn't the one to set up those files.

### Logs

https://mclo.gs/AWZxbVE

### Server Version

1.20.1

### Server Type

Paper

### Discs.json

```json
https://drive.google.com/file/d/1X1jC6ir9ypXmHbz5REXiyx3c6iGLTTPH/view?usp=sharing
```

### Resource pack

https://drive.google.com/file/d/1C7HZBK2zTxZht7EbbByirPeZPCixfuMM/view?usp=drive_link

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Hi thanks for the bug report, don't worry the error is not your fault and you are not missing any files.
I'll fix this when I get home later and I'll release un update with the fix.

**Comment by spartacus04** [comment]
Hi, what is the plugin jar file renamed to in the plugins folder?

**Comment by therealjar** [comment]
Jukebox Extended Reborn | Add custom music discs.103219.jar

**Comment by spartacus04** [comment]
Try removing the | character in the file name

**Comment by therealjar** [comment]
yep that did it haha thanks

**Comment by spartacus04** [comment]
you're welcome, glad to hear you solved it.
