### ISSUE TITLE
[Bug]: Importing to online Generator breaks disc textures

### ISSUE THREAD

**Issue by upro2006** [spartacus04/jext-reborn#145]
### Describe the bug

Imported textures of the resource pack don't seem to work as they don't show up (and become black-gray in-game)
Although imported names and lores work alright.
![image](https://github.com/spartacus04/jext-reborn/assets/90815257/1471f927-909f-4e1c-8b32-b96e1560c73c)

### Steps to reproduce

1. Open the webtool and click 'Import' on the top right corner
2. Import normally, with a Resource pack.zip and a disc.json file
3. Click 'Import' next to 'Discard'
4. Textures go broke

### Expected behaviour

I expected them to show up fine after importing.

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Hi, thanks for the bug report, I just updated the website to fix this
