### ISSUE TITLE
[Bug]: The music still plays after taking the disc out of the jukebox with hopper minecart.

### ISSUE THREAD

**Issue by Kowal9833** [spartacus04/jext-reborn#146]
### Describe the bug

After taking custom discs out of the jukebox using hopper minecart, jukebox continues playing like if it was still there. Even more interestingly, when you break the jukebox after removing the disc, music still continues playing.

### Steps to reproduce

STEP 1. Put a custom disc in a jukebox.
STEP 2. Place a hopper minecart under the jukebox.
(optional) STEP 3. Break the jukebox.

### Expected behaviour

Music stops playing after removing it out of the jukebox/breaking jukebox.

### Server Version

1.20.1

### Server Type

Paper

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Hi, thanks for the bug reports. I noticed that you are submitting multiple bug reports here. I'll be fixing most of them when i get back home later today

**Comment by spartacus04** [comment]
I just fixed this in [58a2555](https://github.com/spartacus04/jext-reborn/commit/58a25555948d1912af1b097635b13928dad4c8ee), I'll release an updated version of the plugin when I fix the other plugin bug you submitted
