### ISSUE TITLE
[Bug]: Placing a block on the jukebox stops the music.

### ISSUE THREAD

**Issue by Kowal9833** [spartacus04/jext-reborn#147]
### Describe the bug

Placing a block on top of the jukebox makes it stop playing music. The bug only happens when the block is being placed on the jukebox by clicking on it with a block, not if a block is being placed by clicking on any other block. Moving blocks with pistons also doesn't trigger the bug.

### Steps to reproduce

STEP 1. Put a custom disc in a jukebox.
STEP 2. Shift+rightclicking on the jukebox, place a block on the jukebox.

### Expected behaviour

The music continuing playing.

### Server Version

1.20.1

### Server Type

Paper

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Fixed in [d9ef0b8](https://github.com/spartacus04/jext-reborn/commit/d9ef0b82cf7401cccf782442f0884e826a2b87f2)
