### ISSUE TITLE
[Bug]: Texture of the disc fragment not showing up after uploading to the tool.

### ISSUE THREAD

**Issue by Kowal9833** [spartacus04/jext-reborn#148]
### Describe the bug

Texture of the disc fragment isn't showing up after uploading it to the tool. I'm not sure if it's a bug or feature request, but it's pretty annoying when there is no sign that I even uploaded the texture (like with the disc texture) and I often must upload it multiple times to be sure.

### Steps to reproduce

STEP 1. Go to the [tool](https://spartacus04.github.io/jext-reborn/).
STEP 2. Click the plus icon on the bottom.
STEP 3. Upload the sound.
STEP 4. Click the disc fragment icon on the pannel on the left.
STEP 5. Click the disc fragment icon on the bottom left.
STEP 6. Upload the texture.

### Expected behaviour

Texture of the disc fragment showing up in the tool after uploading.

### Server Version

1.20.1

### Server Type

Paper

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Just fixed this in latest generator commit
