### ISSUE TITLE
[Bug]: Disc fragment 

### ISSUE THREAD

**Issue by Marotaro** [spartacus04/jext-reborn#151]
### Describe the bug

when I click on a jukebox with a fragment of disc the music of the complete disc plays.

### Steps to reproduce

1. Place a jukebox
2. get any fragment
3. right click with the fragment on the jukebox

### Expected behaviour

not play any music

### Server Version

1.20.1

### Server Type

Paper

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Just fixed this in latest commit
