### ISSUE TITLE
 Add an exclusive GUI for administrators.

### ISSUE THREAD

**Issue by 347180440** [spartacus04/jext-reborn#156]
### Is your feature request related to a problem? Please describe.

Currently, is it only possible to obtain discs through pure commands, and one has to refer to the configured names to find the corresponding discs, which is quite inconvenient.

### Describe the solution you'd like.

The GUI sequentially lists all the music discs configured in 'discs.json', making it convenient for administrators to click and acquire them.

**Comment by spartacus04** [comment]
Hi, that's a nice idea. I'll probably add it in the next update. However right now I am on vacation and I'll add it when I get back

**Comment by spartacus04** [comment]
Hello, thanks for submitting this feature request, I've just published a new update which adds this.
