### ISSUE TITLE
[Bug]: Discs with shift + mouse keys are overloading the server

### ISSUE THREAD

**Issue by WataLaker37821** [spartacus04/jext-reborn#158]
### Describe the bug

when inserting or taking discs to / from jukebox using shift key, when doing it fast, server starts overloading, tps drops to 10, for a couple of seconds, and when i stop doing it , tps becomes normal

### Steps to reproduce

take many discs, or even 2 discs, try fast clicking to insert them all in a jukebox and then taking them back from it, get error in console that server is overloaded and tps drop

### Expected behaviour

no tps drops or server lags when using shift while taking / inserting discs

### Logs

https://pastebin.com/t198LiAw

### Server Version

1.18.2

### Server Type

Purpur

### Jukebox Behaviour

Gui

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Hi, thanks for the bug report. Right now I am on vacation and I can't work on the plugin. I'll fix this when I get back home

**Comment by WataLaker37821** [comment]
Have a nice vacation, i am on a vacation from my job too so we are kinda
similar rn xd

воскресенье, 6 августа 2023 г. пользователь Andrew ***@***.***>
написал:

**Comment by spartacus04** [comment]
Thanks! you have a nice vacation too!

**Comment by spartacus04** [comment]
Hello, thanks for submitting this bug report, I've just published a new update which should fix your bug.
