### ISSUE TITLE
[Bug]: EXTREME TPS LAG when breaking sugarcanes

### ISSUE THREAD

**Issue by WataLaker37821** [spartacus04/jext-reborn#163]
### Describe the bug

today i upgraded my server from 1.18.2 to 1.20.1, i use Purpur, so when players break 2nd sugarcane block from the ground (sugarcane must be already existing on a someone's farm), so when player breaks it, upper blocks of sugarcane stay for some seconds and then break too, but its all with HUGE tps losses, when i removed your plugin, situation became normal again

### Steps to reproduce

1. find a sugarcane farm that was BEFORE server's upgrade
2. start breaking sugarcane, break only 2nd block from ground level
3. get a huge tps losses

### Expected behaviour

no tps loss when breaking sugarcane 

### Server Version

1.20.1

### Server Type

Purpur

### Jukebox Behaviour

Gui

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Hello, thanks for submitting this bug report, I've just published a new update which should fix your bug.
