### ISSUE TITLE
[Bug]: VERY VERY BAD DUPE GLITCH

### ISSUE THREAD

**Issue by Xxcaden9999xX** [spartacus04/jext-reborn#175]
### Describe the bug

On the new gui, if you spam right-click, it will duplicate discs. On the old one, if you spam right-click, it will delete discs. If you break a jukebox, with discs in it, and then place any block, where that jukebox was previously placed, and then break it, it will spit out the same discs that were in the jukebox, you can do this infinitely. This has ruined my server economy 😭

### Steps to reproduce

see above

### Expected behaviour

i expected it to not duplicate infinite discs

### Server Version

1.20.1

### Server Type

Paper

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Hello, I just fixed the duplication bug regarding the jukebox being destroyed. I am extremely sorry about what happened.
As for the first duplication bug you mentioned the plugin under the hood is running [InvUI](https://github.com/NichtStudioCode/InvUI) for displaying and working with inventories and I have no control over it, you can report that bug over to them. However I tried to spam right-click just like how you said I wasn't able to reproduce it.

**Comment by spartacus04** [comment]
I'll now make a new release with the jukebox destruction fix

**Comment by Xxcaden9999xX** [comment]
Thank you so much!! Couldn't find any other plugins that had a GUI and
custom discs. I run a server for a music artist named Overpade nd had added
his discography to the game. I genuinely thank you for making this plugin,
as it has made the server so much more interactive and has given incentive
to play (finding discs in structures/trading etc.) You've made my life a
whole lot easier 😭😭
