### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Cramn1017** [spartacus04/jext-reborn#178]
### Describe the bug

all commands keep telling me there is an internal error how do i fix this i have the protoclib and everything it just wont wo0rk

### Steps to reproduce

w

### Expected behaviour

w

### Server Version

1.20.1

### Server Type

Spigot

### Resource pack

https://www.dropbox.com/s/om1kv0uv759kew2/example%20resourcepack.zip?dl=0&file_subpath=%2Fassets

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Hello, thanks for submitting this bug report, I've just published a new update which should fix your bug.
