### ISSUE TITLE
Generate discs.json on first start and include README file into the online tool

### ISSUE THREAD

**Issue by Quik2007** [spartacus04/jext-reborn#18]
When the plugin is started for the first time, it crashes due to no discs.json file being present in /plugins/JukeBoxExtendedReborn/.
It's not clear that you have to move the discs.json to the directory of the plugin in order to get it to work correctly.
Therefore, it would be good to have a empty discs.json automatically generated.

When using the online tool (https://spartacus04.github.io/jext-reborn/) it is not clear where to move the discs.json.
Also, it is not clear to inexperienced server administrators how to set up a server resource pack.
This information could be provided as a README file in the generated .zip archive.

**Comment by spartacus04** [comment]
Thanks for the feedback I'll try to make it clearer

**Comment by spartacus04** [comment]
An empty discs.json file renders the plugin useless, so i opted to log to the server console a message saying that the plugin is not configured, and a link to the wiki.

As for the online tool i added a readme file just like you suggested.
The readme file tells you to how to set up the resource pack and the rest of the plugin.
