### ISSUE TITLE
[FEATURE REQUEST]: Ability to shuffle, loop, and change volume of music from the GUI.

### ISSUE THREAD

**Issue by Zander-GitHub** [spartacus04/jext-reborn#198]
### Is your feature request related to a problem? Please describe.

I really like the plugin as there’s none like it, but me and my friends use it in a survival world where we all build cities. We want to have jukeboxes around our towns that play ambience and music so we can add to the environment and immersion. Whenever somebody uses the jukebox, the music plays very loud globally and not from the jukebox.

### Describe the solution you'd like.

The jukebox GUI already feels very bland and empty and I feel it could benefit from from a rework, such as the ability to change the volume, shuffle and possibly have a loop feature standalone.

### Describe alternatives you've considered.

As of now, can’t find a workaround that doesn’t involve commands or other hackery.

**Comment by spartacus04** [comment]
Hello, I'll take into consideration your idea for a future update, like you I think the jukebox gui is really minimal and I would love to update it by adding this features.

As a workaround right now you can check out [jukelooper](https://gitlab.com/ranull/minecraft/jukelooper/-/merge_requests/3?commit_id=5250071b0f4ea6c6836a9fbc2b7623e568f5f3af), the owner of the plugin is taking a long break, as such I've made my own fork to support jext reborn and update it to newer versions.
