### ISSUE TITLE
[BUG] not initialising config?

### ISSUE THREAD

**Issue by netcore10** [spartacus04/jext-reborn#20]
**Describe the bug**
Config not initialising - No directory?
**To Reproduce**

**Expected behavior**
to initialise

**Logs**
https://mclo.gs/FBxaRaY

**Enviroment (please complete the following information):**
 - Server type: paper
 - Version 1.19.2

**Additional context**

**Comment by spartacus04** [comment]
Hi, thanks for the bug report, it was a little oversight related to the first plugin run.
Basically the plugin warned you that you didn't have a discs.json file (used for the custom discs) and then didn't copy and load the default config.

I just fixed the issue but i'm having some problems connecting to the spigot maven repo, so i'll upload the new fixed version a soon as i can. I'll let you know when it'll be online.

**Comment by spartacus04** [comment]
Should be working in latest release [5f6f81a](https://github.com/spartacus04/jext-reborn/commit/5f6f81aa8f97911746b386c2f3c8b77a11eba4be).

If it's still not working please open a new issue.
