### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by meloman-rrr** [spartacus04/jext-reborn#203]
### Describe the bug

Whenever i execute any command, the example of how should i write it just pops-up in the chat. It happens with any command of the plugin. (the resourcepack and discs.json was made via built-in tool)
![изображение_2023-11-09_043101082](https://github.com/spartacus04/jext-reborn/assets/150307817/f6aaf803-c3c6-4d57-8f12-0a79f37b9923)

### Steps to reproduce

1. open your chat
2. write any command that the plugin has
3. press enter to execute it

### Expected behaviour

The command should execute the intended things, such as giving the player a music disc

### Server Version

1.16.5

### Server Type

Spigot

### Resource pack

https://www.dropbox.com/scl/fi/77rdjmuhfhcjnd5fkscgn/3mat_custom_discs.zip?rlkey=d5urd5dbet7fpfarezalskd1i&dl=1

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [x] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Hello, thanks for submitting this bug report, I've just published a new update which should fix your bug.
