### ISSUE TITLE
Custom music won't play

### ISSUE THREAD

**Issue by marcelschoen** [spartacus04/jext-reborn#21]
I created a resource pack with your online tool, with one custom OGG file in it. When I play that disc, I get no sound on the client at all. The standard discs work. I have attached the files that I created. The plugin config:

discs.json:
```
[
  {
    "title": "numb",
    "author": "Disc author",
    "disc-namespace": "music_disc.numbdiscauthor",
    "model-data": 1,
    "creeper-drop": true,
    "lores": [
      "This is the lore of the disc",
      "",
      "You can have multiple lines.",
      "",
      "If you dont want any lore you can leave this empty."
    ],
    "loot-tables": []
  }
]
```
config.json:
```
{
  // Language mode [ auto or custom ]
  "lang": "auto",

  // Kick players who decline server resource pack
  "force-resource-pack": true,

  // Ignore if player somehow failed to download the resource pack
  "ignore-failed-download": false,

  // Allow/Disallow overlapping music (two jukeboxes playing at the same time)
  "allow-music-overlapping": false,

  // Allow/Disallow plugin metrics (no personal data is going to be collected)
  "allow-metrics": true
}
```

[open me.zip](https://github.com/spartacus04/jext-reborn/files/9892355/open.me.zip)

**Comment by spartacus04** [comment]
Hi, Sorry to hear that you are having issues with the plugin.

Have you added the your_pack_name file as a server resource pack?

I noticed that the bundle the website gave you, the resource pack file generated without a .zip format, maybe that's the issue.

**Comment by marcelschoen** [comment]
Well the server asked me to redownload the resource pack. I have a script-based update for the resource pack, which automatically updates package (with a different filename), and updates the SHA1 hash in "server.properties". Do you have an example of a working resource pack maybe? Then I could compare. Maybe there are limits on the OGG filesize or something?

**Comment by marcelschoen** [comment]
Dammit... there error is somewhere in my re-packaging script. It actually works with the archive I downloaded from your tool website. Sorry, forget it then.

**Comment by marcelschoen** [comment]
Actually, it may be the problem that I merge multiple resource packs, and one of them apparently overwrites the file "/assets/minecraft/models/item/music_disc_11.json". Is that file crucial for the functionality? Is there a way to use another one?

**Comment by spartacus04** [comment]
Yes the file Is crucial as It creates the custom model data for all the discs, you could probably patch It by using another disc (the tutorial for creating the discs manually could help you) or by merging the JSON files manually
