### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by pingarss** [spartacus04/jext-reborn#210]
### Describe the bug

I cant hear the music i added. I have done everything with the tool and i did it right, i use itemsadder so i merged resourcpacks, and it doesnt see mto work because i have disc texture, i have its name lore everything except sound. Help?! (no errors aswell)

### Steps to reproduce

Made resourcep ack with the tool
Uploaded resource pack to itemsadder and merged it together
Added disc.json to the jetx folder
followed all instructions and did /iazip for pack to set up.

### Expected behaviour

Sounds to work.

### Server Version

1.20.1

### Server Type

Paper

### Discs.json

```json
https://failiem.lv/u/xws883mzz7
```

### Resource pack

https://failiem.lv/u/vc8au9v96h

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Hello, thanks for submitting this bug report, I've just published a new update which should fix your bug.
