### ISSUE TITLE
[Bug]: Very Slow Loading

### ISSUE THREAD

**Issue by GameMaster5117** [spartacus04/jext-reborn#219]
### Describe the bug

Using the Tool, a 9 second audio file was taking about 5 minutes to load. I stopped running it after that.

### Steps to reproduce

Go to [https://spartacus04.github.io/jext-reborn/](https://spartacus04.github.io/jext-reborn/). Click on the +. Add the file. Set to 1.20.2 High Quality. Set to no creeper, structure, or fragments. Name everything in it TEST.

### Expected behaviour

I though it'll take under a minute, this is very slow.

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by GameMaster5117** [comment]
Sorry if I did anything wrong, I'm new to GitHub.

**Comment by spartacus04** [comment]
Hello, thanks for submitting this bug report, I've just published a new update which should fix your bug.
