### ISSUE TITLE
[question] Does 3D sound and distance still work?

### ISSUE THREAD

**Issue by netcore10** [spartacus04/jext-reborn#22]
Does 3D sound and distance still work? If so, do you know what i need to edit in a resourcepack to get it working properly?

**Comment by spartacus04** [comment]
3D sound works out of the box with JEXT so no problem with that,
as for the distance I didn't add the distance feature yet, but I'll probably add it in a future update.

**Comment by spartacus04** [comment]
If you have any further questions please reopen the issue
