### ISSUE TITLE
Online tool disc remove does not work

### ISSUE THREAD

**Issue by marcelschoen** [spartacus04/jext-reborn#23]
- Upload two OGG files in the online tool (with simple filenames with no blanks etc.)
- Don't enter anything in any input fields
- Click "GENERATE" button 
- The generated archive contains both discs
- Now delete one disc
- It disappears in the GUI
- Click "GENERATE" button again
- The newly generated archive still contains both discs (in the "discs.json", but also both OGG files are still in the archive etc.)

**Comment by marcelschoen** [comment]
I also had a situation where I added a second disc, then removed the first one, and when I clicked "GENERATE", an error message appeard: "Add at least a disc" - despite the UI still showing one disc (the 2nd one I uploaded).

**Comment by spartacus04** [comment]
Hi thanks for the bug report again, The generator website is in the middle of being fully reworked, so the fix might take a bit longer, still it'll be avaiable as soon as possible

**Comment by spartacus04** [comment]
Fixed in latest website version
