### ISSUE TITLE
[Bug]: unable to import discs.json

### ISSUE THREAD

**Issue by fowlerkenneth** [spartacus04/jext-reborn#237]
### Describe the bug

when i try to import a previously generated datapack, it will not regisiter the discs.json file but when i try an older version it works

### Steps to reproduce

[discs.json](https://github.com/spartacus04/jext-reborn/files/14346418/discs.json)]
visit https://spartacus04.github.io/jext-reborn/
click on import
click on discs.json
choose attached file

### Expected behaviour

to load my current discs.json file in order to update and add more discs

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by Gavin-Krikstone** [comment]
The reason this is happening is because you are importing only the json file. On the import screen you much click the discs.json option, import the json file, THEN ALSO click resource pack and import that as well. both options must have the file for the import to work.

**Comment by spartacus04** [comment]
Hello, thanks for submitting this bug report, I've just published a new update which should fix your bug.
