### ISSUE TITLE
Resource pack created with online tool won't work

### ISSUE THREAD

**Issue by marcelschoen** [spartacus04/jext-reborn#24]
I created the attached resource pack with the online tool. It contains only one song. When I play it (by disc or by command) I don't get any sound. Any other disc works.

Somehow I had it working once a few hours ago, but I can't get it working again. I currently fail to identify the problem. As I said, the attached source file is exactly the one downloaded from the online tool, with no changes whatsoever. Of course I also updated the "discs.json" in the plugin config accordingly.

I must be doing something wrong, but I can't figure it out.

[jukebox-numb.zip](https://github.com/spartacus04/jext-reborn/files/9893298/jukebox-numb.zip)

**Comment by spartacus04** [comment]
The resource pack looks valid to me, I just tried to use it with a dummy discs.json and it's working. Do the commands autocomplete the disc namespace?

**Comment by marcelschoen** [comment]
Yes, the command autocomplete works. No visible issue there. What does your "dummy" discs.json look like, exactly?

**Comment by spartacus04** [comment]
Mine looks like this

```

    {
        "title": "Disc name",
        "author": "disc author",
        
        "disc-namespace": "music_disc.numbdiscauthor",
        "model-data": 1,
        
        "creeper-drop": false,
        "lores": [],
        "loot-tables": []
    },
]
```

**Comment by marcelschoen** [comment]
I have identified the source of the problem - it was my stupidity! I have a somewhat complicated setup with a test and a prod server, and I apply changes to them with the ansible scripting tool. I just had made certain changes in the wrong place, and the server just didn't actually use the right resource pack. Sorry for that!

**Comment by spartacus04** [comment]
No worries, i'm happy that you solved the problem.
