### ISSUE TITLE
[BUG] Online tool not generating resource pack a zip file

### ISSUE THREAD

**Issue by BookWyrm114** [spartacus04/jext-reborn#25]
**Describe the bug**
the everything is generated, but the resource pack has no file extension and you need to manually add .zip to the file name to use it

**To Reproduce**
add some songs on the online tool, press generate, and unzip the file, realize there's no .zip file for the resource pack

**Expected behavior**
for the resource pack zip file to be generated correctly

**Additional context**
<img width="520" alt="image" src="https://user-images.githubusercontent.com/79489385/198851559-6ed06bf4-a5f6-47b7-8d7a-cba14d900538.png">

**Comment by spartacus04** [comment]
As mentioned in #23 the disc generation website is being reworked entirely, still I just pushed a temporary fix that adds the .zip extension.
