### ISSUE TITLE
[BUG] music doesn't fade with distance and players can't hear custom music if they aren't near the jukebox when the music starts

### ISSUE THREAD

**Issue by BookWyrm114** [spartacus04/jext-reborn#26]
**Describe the bug**
when you start playing a custom music disc, you will continue to hear the song until it finishes or you eject the disc, even if you move far enough away to unload the chunks that the jukebox is in, however vanilla music disc sound does fade with distance. Also, if you start a custom song and a player who wasn't there when you started it arrives, they will be unable to hear it

**To Reproduce**

fading issue:
- play a custom music disc
- move as far away as you can and notice it won't fade.

unable to hear music issue:

- have one player/account start a custom disc
- have another player/account (that wasn't close enough to hear the music when it started) teleport or somehow go near the jukebox, and notice that that player/account does not hear the music

**Expected behavior**
for the custom disc behavior to mirror vanilla behavior

**Enviroment (please complete the following information):**
 - Server type: purpur
 - Version: 1.19.2

**Comment by spartacus04** [comment]
Thanks for the bug report.

For the first issue i should make clear that stereo music isn't compatible with distance, so make sure your audio is in mono (in the generator website rework i'm adding an option to make it mono automatically).

I will also probably support stereo in the future (probably next major update).

As for the second report the behaviour is the expected one, the discs work just like the vanilla ones. 
If you need that other behaviour I could probably add it as a togglable option in the config in the next update thought.

**Comment by spartacus04** [comment]
I just added a toggle on the website to allow mono audio.
