### ISSUE TITLE
[Bug]: configure web gui bug

### ISSUE THREAD

**Issue by francycyborg75** [spartacus04/jext-reborn#274]
### Describe the bug

i was doing the tutorial in the JEXT documentation but when i do the /jext webui config and i click the link it gives me a 404 error page. before telling me this bug as fixed i looked at the bug page and there is one but it says is fixed and i istalled the latest version of the plugin.

### Steps to reproduce

write in chat /jext webui config and click the link or paste it in the web page

### Expected behaviour

i expected to open an web editor

### Logs

they are no error logs.

### Before submitting the issue

- [x] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by francycyborg75** [comment]
ps mi puoi scrivere in italiano :)

**Comment by spartacus04** [comment]
Si, non ho ancora pubblicato l'aggiornamento dato che devo aggiustare la connessione alla webui in un altro bug. Probabilmente nei prossimi giorni sistemerò quel bug e pubblicherò l'aggiornamento. Nel mentre puoi semplicemente rimpiazzare l'URL da `jext.reborn` a `jext-reborn`

**Comment by francycyborg75** [comment]
> Si, non ho ancora pubblicato l'aggiornamento dato che devo aggiustare la connessione alla webui in un altro bug. Probabilmente nei prossimi giorni sistemerò quel bug e pubblicherò l'aggiornamento. Nel mentre puoi semplicemente rimpiazzare l'URL da `jext.reborn` a `jext-reborn`

Grazie :)

**Comment by francycyborg75** [comment]
> Si, non ho ancora pubblicato l'aggiornamento dato che devo aggiustare la connessione alla webui in un altro bug. Probabilmente nei prossimi giorni sistemerò quel bug e pubblicherò l'aggiornamento. Nel mentre puoi semplicemente rimpiazzare l'URL da `jext.reborn` a `jext-reborn`

Cmq lo so che non c'entra niente... ma ti devo dire che questo è uno dei plugin migliori che abbia mai istallato. Continua con i tuoi progetti bro!
