### ISSUE TITLE
[Bug]: Failed to fetch (IT)

### ISSUE THREAD

**Issue by francycyborg75** [spartacus04/jext-reborn#275]
### Describe the bug

When i connect to jext server,after i put the ip and the password  it says failed to fetch(scusa se ti rompo ma perfavore aiutami)

### Steps to reproduce

Go to minecraft and send the command for the web gui. After you put the ip and password it give you the text

### Expected behaviour

Web edito

### Logs

Error connecting to jext server

### Server Version

1.19.4

### Server Type

Spigot

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by francycyborg75** [comment]
@spartacus04 perfavore rispondimi

**Comment by spartacus04** [comment]
Grazie ad un altro bug report ho individuato il problema e sto tentando di risolverlo, come workaround puoi generare la resourcepack senza connetterti al plugin e scaricarla manualmente

**Comment by francycyborg75** [comment]
> Grazie ad un altro bug report ho individuato il problema e sto tentando di risolverlo, come workaround puoi generare la resourcepack senza connetterti al plugin e scaricarla manualmente

Quindi come posso risolvere il problema che non ho capito?
Perchè mi serve veramente tantissimo

**Comment by spartacus04** [comment]
Per configurare il plugin puoi semplicemente modificare il file `JukeboxExtendedReborn/config.json` nella cartella dei plugin. ([qui](https://spartacus04.github.io/jext-reborn/documentation/config/) puoi trovare la documentazione la documentazione)

Per i dischi vai al sito https://spartacus04.github.io/jext-reborn/
Una volta fatto al posto di collegarti al plugin comincia a aggiungere i dischi musicali normalmente, infine clicca su genera, e una volta che avrà scaricato il file spostalo al percorso `JukeboxExtendedReborn/resource-pack.zip` nella cartella dei plugin. Se usi anche Geyser, puoi scaricare il relativo pacchetto e inserirlo nella cartella delle risorse.

Se hai altri dubbi non esitare a chiedere

**Comment by francycyborg75** [comment]
> Per configurare il plugin puoi semplicemente modificare il file `JukeboxExtendedReborn/config.json` nella cartella dei plugin. ([qui](https://spartacus04.github.io/jext-reborn/documentation/config/) puoi trovare la documentazione la documentazione)
> 
> Per i dischi vai al sito https://spartacus04.github.io/jext-reborn/ Una volta fatto al posto di collegarti al plugin comincia a aggiungere i dischi musicali normalmente, infine clicca su genera, e una volta che avrà scaricato il file spostalo al percorso `JukeboxExtendedReborn/resource-pack.zip` nella cartella dei plugin. Se usi anche Geyser, puoi scaricare il relativo pacchetto e inserirlo nella cartella delle risorse.
> 
> Se hai altri dubbi non esitare a chiedere

Quindi afforza devo fare che la texture pack è hostata dal plugin?

**Comment by francycyborg75** [comment]
> Non per forza, puoi anche hostarla da un altra parte senza problemi, ricordati solo di disabilitare `enable-resource-pack-host` nella configurazione se non la usi.

Già fatto e ho generato pure la texture ma nei dischi non mi appare niente.. cosa sta sbagliando? Scusa la mia ignoranza ma è un pò difficile capire questo plugin per me

**Comment by spartacus04** [comment]
Tranquillo, con l'ultimo aggiornamento ho tentato di rendere il plugin più facile da comprendere ma dovendo gestire anche le texture è un po difficile.

Se nel terminale del server provi a digitare `/jext discs` come autocompletamento ti esce qualcosa oppure no?
Altrimenti prova a impostare il campo `resource-pack-sha1` nel file `server.properties`

**Comment by francycyborg75** [comment]
> Tranquillo, con l'ultimo aggiornamento ho tentato di rendere il plugin più facile da comprendere ma dovendo gestire anche le texture è un po difficile.
> 
> Se nel terminale del server provi a digitare `/jext discs` come autocompletamento ti esce qualcosa oppure no? Altrimenti prova a impostare il campo `resource-pack-sha1` nel file `server.properties`

Mo ho tolto dalla mia texture pack il disco e lo sto rifacendo da capo anche se l'altra volta non funzionava il merge delle due texture pack e spero che stavolta funzioni poi apro il server e ti dico

**Comment by spartacus04** [comment]
si inviamela pure, puoi inviarlo a spartacus04 su discord, oppure semplicemente caricalo su google drive e poi mi invii il link qui. Ci do un occhiata stasera quando torno a casa

**Comment by francycyborg75** [comment]
> si inviamela pure, puoi inviarlo a spartacus04 su discord, oppure semplicemente caricalo su google drive e poi mi invii il link qui. Ci do un occhiata stasera quando torno a casa

Pultroppo stasera non te la riesco a inviare perchè i file sono nel pc e non lo riesco a toccare ma domani pomeriggio(cioè oggi pomeriggio) ti mando il link di google drive e mi dici cosa sto sbagliando :)

**Comment by francycyborg75** [comment]
ti ho inviato la richiesta di amicizia appena l'accetti ti mando la mia texture pack
