### ISSUE TITLE
an internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by Norniiie** [spartacus04/jext-reborn#282]
### Describe the bug

When i use the command for the disc there comes an error and the logs say that it is disabled

### Steps to reproduce

wheb i start the server it says in the logs that
[16:30:10 WARN]: [JEXT] Async task for JukeboxExtendedReborn v2.0.1 generated an exception
and when i use the /disc command it says that there is an internal error and it comes with every disc also with the discs from the plugin 

### Expected behaviour

i wanted to use a custom disc

### Logs

5.4.2024, 18:38:54: org.bukkit.command.CommandException: Cannot execute command 'disc' in plugin JukeboxExtended v1.2.0 - plugin is disabled. 5.4.2024, 18:38:54: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] 5.4.2024, 18:38:54: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] 5.4.2024, 18:38:54: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?] 5.4.2024, 18:38:54: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:444) ~[?:?] 5.4.2024, 18:38:54: 	at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[?:?] 5.4.2024, 18:38:54: 	at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?] 5.4.2024, 18:38:54: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2230) ~[?:?] 5.4.2024, 18:38:54: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2190) ~[?:?] 5.4.2024, 18:38:54: 	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?] 5.4.2024, 18:38:54: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] 5.4.2024, 18:38:54: 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?] 5.4.2024, 18:38:54: 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?] 5.4.2024, 18:38:54: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?] 5.4.2024, 18:38:54: 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?] 5.4.2024, 18:38:54: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1550) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-350] 5.4.2024, 18:38:54: 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Server Version

1.20.4

### Server Type

Spigot

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by Norniiie** [comment]
okay i fixxed the error i had an old procotollib but now it says 
[JEXT] resource-pack.zip not found, please provide it in the plugin directory

**Comment by spartacus04** [comment]
Did you configure the resource pack host or are you hosting the resource pack somewhere different?

**Comment by spartacus04** [comment]
Stale issue, closing this
