### ISSUE TITLE
disc autocomplete not working

### ISSUE THREAD

**Issue by spartacus04** [spartacus04/jext-reborn#283]
> About the commands you suggested as of now you can just use `/jext discs` and check the autocomplete, but i should probably make something like a /listdiscs

There is no `/jext discs` command. There is `/jext disc` but the autocomplete on that puts in player names, not discs.

_Originally posted by @Legendile7 in https://github.com/spartacus04/jext-reborn/issues/257#issuecomment-2041136286_

**Comment by Legendile7** [comment]
Fixed with latest update to documentation, config was incorrect. There is still no `/jext discs` command but `/jext disc` autocompletes correctly now.

**Comment by spartacus04** [comment]
In the next update I'll add the ability to execute `/jext disc` without any disc namespace to output all the disc namespaces.
