### ISSUE TITLE
[Bug]: Resource pack download failed, please re-join to try again.

### ISSUE THREAD

**Issue by nuttapillar** [spartacus04/jext-reborn#295]
### Describe the bug

When I add this plugin to the server, Java players get the error mentioned in the title, and are unable to join the server. As soon as I remove the plugin, it all works fine again. This was happening a few versions ago, and I decided to try the plugin again after some updates, but it's still doing it.

### Steps to reproduce

Create a server resource pack containing custom sounds.
Use the online generator to make a JEXT pack.
merge the JEXT pack with existing custom resource pack.
Notice that the pack downloads and runs just fine on its own.
Add the JEXT plugin.
Suddenly people cannot join the server.

### Expected behaviour

I expect the pack to continue working, even with the plugin running.
![image](https://github.com/spartacus04/jext-reborn/assets/22978620/4ef9bc07-5963-47b2-bc9b-8fee1033d375)

### Server Version

1.20.4

### Server Type

Paper

### Resource pack

https://www.dropbox.com/scl/fi/8pqp2qdp2nhfddo43wj8t/MDU25.zip?rlkey=eryffo8mr5ib4telxyuucmpta&dl=1

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Is the 9871 port open on your server? If not you need to disable the `enable-resource-pack-host` in the config and load the resourcepack by using something like dropbox. Also check if the `force-resource-pack` is enabled in the config, you can disable the kicking behaviour.

If you decide to not open the port you also need to create a sha1 of the resourcepack and add it to the `server.properties`

**Comment by nuttapillar** [comment]
force resource pack is already false. and I use mc-packs.net to host the pack, which creates a sha1, which i have put in the properties. I don't think 9871 is open. but since i have it hosted on mc-packs, i can keep that closed, right?

**Comment by spartacus04** [comment]
Yes, you can keep it closed. I just noticed I inadvertently inverted the condition for failed resource pack downloads, I'll publish an update rn which fixes this. You should also disable the resource pack host if you are not using it
