### ISSUE TITLE
[Bug/Regression]: Unable to download created resourcepack

### ISSUE THREAD

**Issue by Crafty-The-Fox** [spartacus04/jext-reborn#298]
### Describe the bug

Once creating a resource pack, your unable to download it.

### Steps to reproduce

1. Import a song
2. Click Generate
3. After generating, the text is still layered ontop of the buttons, and the buttons dont seem to work or do anything at all.

### Expected behaviour

Ability to download the pack and apply it to the server

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by Crafty-The-Fox** [comment]
![image](https://github.com/spartacus04/jext-reborn/assets/59181698/5cb49743-bd08-4670-8d74-90bd6e0f7c7b)

**Comment by Crafty-The-Fox** [comment]
This also seemingly happens on the desktop version, but i dont have an image for that one.

**Comment by Crafty-The-Fox** [comment]
This seemingly is fixed in b4063b8, but i cant test it on the website, as there is only the app downloads in github actions.

**Comment by spartacus04** [comment]
Fixed in https://github.com/spartacus04/jext-reborn/commit/76118e21ecc059b280347a0d27dddf75bc5cecec
