### ISSUE TITLE
[Bug/Regression]: GUI Scale very off on desktop application

### ISSUE THREAD

**Issue by Crafty-The-Fox** [spartacus04/jext-reborn#299]
### Describe the bug

GUI Scale is very off on the desktop application
![Capture2](https://github.com/spartacus04/jext-reborn/assets/59181698/2a106eb5-7a4a-456e-9883-3edc7cdb1342)
![Capture3](https://github.com/spartacus04/jext-reborn/assets/59181698/bad69215-9ed7-4b62-92cf-82154b7dc1ff)
![Capture](https://github.com/spartacus04/jext-reborn/assets/59181698/bcf5df8c-ae09-46d7-8411-ae697967d3fb)

### Steps to reproduce

1. Open the application

### Expected behaviour

The icons/application not being large, and the ability to scroll when needed.

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by Crafty-The-Fox** [comment]
It also dosent really get any better if you resize the window. You can see more things but the sizing is still way off.

**Comment by Crafty-The-Fox** [comment]
Also, i ended up searching in the actions and downloaded an older version. It works fine on [cd8eef6](https://github.com/spartacus04/jext-reborn/commit/cd8eef69cd552a3f4ce3614b584b2853b49bd03e).

There must have been a change to how the generation window was, and the buttons do actually work correctly and i can download the resource pack.

**Comment by Crafty-The-Fox** [comment]
oh yeah, the color picker dosent work either on the current version, but does on this version.

**Comment by spartacus04** [comment]
Thanks for both of the bug reports, I don't really know why these bug happened. They only appeared after the website had been built. It's probably some dependency doing something strange, I'll check the commits to sent me for the changes. Thanks for the lead!

**Comment by spartacus04** [comment]
Fixed in https://github.com/spartacus04/jext-reborn/commit/76118e21ecc059b280347a0d27dddf75bc5cecec
