### ISSUE TITLE
[Bug]: The plugin does not add disks

### ISSUE THREAD

**Issue by tweeg939** [spartacus04/jext-reborn#307]
### Describe the bug

The plugin does not add disks
I am using paper latest version for version 1.18.2
Also JEXT 2.0.4
And I use the Jext plugin manager application

I am not very familiar with English, so I may make mistakes during the dialogue, I apologize. ( i am using translator)

### Steps to reproduce

1.Add a disk in the Jext plugin manager application
2.Restart the plugin
3.I reboot the server for sure
4.I check for the presence of records in the game

### Expected behaviour

I'm waiting for the plugin to work

### Logs

https://mclo.gs/HsuSR7y

### Server Version

1.18.2

### Server Type

Paper

### Resource pack

https://download.mc-packs.net/pack/e8689f19f25b459a772f9c3b893faffba2b41f83.zip

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
This may be a stupid question, but did you click the apply to jext server button? or did you download the resourcepack and  applied it to server in any way?

**Comment by spartacus04** [comment]
The plugin should be compatible with all versions >= 1.14 but I only tested it on the latest version. I'll make sure to test it in lower versions to check the problem.

**Comment by spartacus04** [comment]
Fixed in latest release
