### ISSUE TITLE
I cant seem to connect to the web ui.

### ISSUE THREAD

**Issue by ItsTNJS** [spartacus04/jext-reborn#309]
### Describe the bug

I installed the plugin, and have been trying to get the web ui working, I setup a password in config, and did everything i needed to, but tit gives me the same error.

`TypeError:` Failed to fetch
    at window.fetch (https://spartacus04.github.io/jext-reborn/_app/immutable/chunks/entry.jWcBaZOX.js:1:1667)
    at mu (https://spartacus04.github.io/jext-reborn/_app/immutable/chunks/extensions.DkwAiHxZ.js:19:30007)
    at async https://spartacus04.github.io/jext-reborn/_app/immutable/nodes/3.ByPebUuM.js:3802:31418`

### Steps to reproduce

[jext-logs.txt](https://github.com/spartacus04/jext-reborn/files/15045666/jext-logs.txt)

### Expected behaviour

Work as normal.

### Logs

![image](https://github.com/spartacus04/jext-reborn/assets/122917107/338caf52-a7b2-4f5e-a591-70d4a2b19130)

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by ItsTNJS** [comment]
It could be a issue with the port, if i set the port to the same as my server (25565) will it function as expected?

**Comment by spartacus04** [comment]
Unfortunately it's a problem with https. For now you need to either enable unsafe content for the website on your browser or use the desktop app.

In the future i'm planning to switch to websockets to fix this problem.

**Comment by ItsTNJS** [comment]
> Unfortunately it's a problem with https. For now you need to either enable unsafe content for the website on your browser or use the desktop app.
> 
> In the future i'm planning to switch to websockets to fix this problem.

I also tried using the desktop app and it still did not want to connect. Could it be an issue with winows?

**Comment by ohmygyatos** [comment]
how did you solve?
