### ISSUE TITLE
Multi-disc player GUI

### ISSUE THREAD

**Issue by marcelschoen** [spartacus04/jext-reborn#32]
It would be great to have a multi-disc UI similar as this other jukebox plugin does it:

https://www.spigotmc.org/resources/%E2%AD%90-jukebox-plus-%E2%AD%90-better-jukeboxes-custom-discs-songs.87750/

**Comment by spartacus04** [comment]
That could be useful, I'll probably add it in the next update.
I'll make the feature opt-in thought as the goal of the plugin is to be as close to vanilla as possible.

**Comment by spartacus04** [comment]
The custom jukebox gui has been added in the latest update. You can opt-in by enabling the jukebox-gui option in the config
