### ISSUE TITLE
[Bug]: Fragment auto converts to music disc.

### ISSUE THREAD

**Issue by NekrosBurek** [spartacus04/jext-reborn#323]
### Describe the bug

Once fragment has been added to chest (any amount) close inventory and open chest again, the fragment is converted to music disc, i would like it to still stay a fragment so players need to find them and craft the music discs.

### Steps to reproduce

1. Give yourself few fragments
2. Put fragments in chest
3. Close inventory/chest
4. Open a chest it has music disc instead of fragments

### Expected behaviour

When fragment is put into chest and chest is opened again it should stay as fragment

### Server Version

1.20.4

### Server Type

Paper

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Fixed in latest release
