### ISSUE TITLE
[Bug]: Can't open admin menu

### ISSUE THREAD

**Issue by NekrosBurek** [spartacus04/jext-reborn#327]
### Describe the bug

When running the /jext admingui i am getting

> `An internal error occurred while attempting to perform this command`

I am running the server with java 17

### Steps to reproduce

1. Start the server
2. run /jext admingui command

### Expected behaviour

It should open the GUI

### Logs

https://paste.nekroplex.com/qihiziruno.properties

### Server Version

1.20.4

### Server Type

Spigot

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Hello, thanks for reporting this issue. This is actually an issue with a dependency used by the plugin. They already fixed it on their end and a fix is coming in the next update
