### ISSUE TITLE
[Bug]: jext.userjukebox permission not working

### ISSUE THREAD

**Issue by BlazingPatriot** [spartacus04/jext-reborn#329]
### Describe the bug

Non-oped players cannot put plugin music discs or vanilla music discs into jukebox, even if they have the jext.usejukebox permission. Hoppers can still place music discs into jukebox

### Steps to reproduce

1.Download Jext and LuckPerms
2.Give default group in LuckPerms the jext.usejukebox permission and apply
3. Players with default group still can not insert music disc into jukebox

### Expected behaviour

Players should be able to place music discs into jukebox with jext.usejukebox permission

### Server Version

1.20.4

### Server Type

Spigot

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
I've just tested this and I wasn't able to replicate the issue. Perhaps it's being blocked by a permission plugin like Worldguard or Griefprevention.

**Comment by BlazingPatriot** [comment]
Worldguard seems to be the culprit, thanks!

**Comment by A-Kevin1217** [comment]
> Worldguard seems to be the culprit, thanks!

Hello, how did you solve this problem?

**Comment by BlazingPatriot** [comment]
Unfortunately just had to disable worldguard
