### ISSUE TITLE
Wireless Jukebox (aka iPod)

### ISSUE THREAD

**Issue by marcelschoen** [spartacus04/jext-reborn#34]
A new custom item could be added - one that is essentially a portable jukebox. One that you can click at while in your inventory to open its UI and make it play music. Essentially making it a portable disc player. Of course this can essentially be achieved by the command for playing music, but commands are just not a very immersive way to do stuff...

**Comment by marcelschoen** [comment]
BTW, maybe this can also be done by using a plugin like "ExecutableItems" or "ItemsAdder", using the command of your plugin. I'll probably give that a try.

**Comment by spartacus04** [comment]
Using a command, just like you said would be the idea.
As i already said the goal of the plugin is to keep things as vanilla-like as possibile, so i'm not going to add a custom item, but a command to run the jukebox UI that i'm adding.

**Comment by spartacus04** [comment]
I've added the /jukeboxgui command in the latest update which opens a player specific jukebox gui. To use it a player must have the jext.jukeboxgui permission node
