### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DemarcoFC** [spartacus04/jext-reborn#345]
### Describe the bug

Errors in console and discs are not being generated via command anymore.

### Steps to reproduce

Loading the plugin on my server with the newest update. I was not having any errors on the last version.

### Expected behaviour

No errors.

### Logs

https://mcpaste.io/0ce9de956a02f667

### Server Version

1.20.4

### Server Type

Spigot

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Fixed in latest update
