### ISSUE TITLE
[BUG] Plugin wont start when custom is set in config languages

### ISSUE THREAD

**Issue by AshiroKun** [spartacus04/jext-reborn#35]
**Describe the bug**
Not sure what happened but I think I changed the config for languages from auto to custom and it broke.

**To Reproduce**
1. Go to the config and change it from auto to custom
2. restart server

**Logs**
[pastebin](https://pastebin.com/US8nA5Ef/)).

**Enviroment:**
 - Server type: PurpurMC
 - Version: 1.19

**Comment by AshiroKun** [comment]
https://pastebin.com/US8nA5Ef

**Comment by spartacus04** [comment]
Yea, i've been aware of this bug, and I already made a fix for it, but I didn't make a new release yet, as I was waiting to add some new features. I'll make a release right now with the fix.

**Comment by spartacus04** [comment]
Just made a new release with the fix
