### ISSUE TITLE
[Bug]: Error connecting to the JEXT server

### ISSUE THREAD

**Issue by LinkIT3** [spartacus04/jext-reborn#364]
### Describe the bug

In the web UI when i try to connect to the server I always receive this error: 
```
TypeError: Failed to fetch
    at window.fetch (https://spartacus04.github.io/jext-reborn/_app/immutable/chunks/entry.CzN3TDOu.js:1:1667)
    at gu (https://spartacus04.github.io/jext-reborn/_app/immutable/chunks/extensions.DSzSdg-Y.js:19:30137)
    at async https://spartacus04.github.io/jext-reborn/_app/immutable/nodes/4.ssY_f0Df.js:1:14065
```

### Steps to reproduce

1. In Minecraft I type `/jext webui`
2. I click on the generated link
3. In the browser I enter the password

### Expected behaviour

Normally it should connect to the server and let you change settings

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Closed due to #399
