### ISSUE TITLE
[FEATURE REQUEST] Option to disable chat messages / silently use commands.

### ISSUE THREAD

**Issue by AshiroKun** [spartacus04/jext-reborn#37]
**Is your feature request related to a problem? Please describe.**
If you could implement a way to disable it from sending a chat message to the player on music play and music stop.

**Describe the solution you'd like**
It would be pretty cool to make it so that it silently plays the music without any notification message being sent to the player. Can be useful for background music through worldguard regions etc.

**Describe alternatives you've considered**
I know its possible to just delete the messages in the lang file but its not that efficient as this option I am proposing.

Sounds like a simple feature but would bring more flexibility with the plugin in my opinion!

**Comment by spartacus04** [comment]
I could probably add a silent mode for the config.

**Comment by spartacus04** [comment]
Added in [730a40d](https://github.com/spartacus04/jext-reborn/commit/730a40dd575c85eac59f8f1361fcdb6b5373753e).

I'm currently working on the next major update. It'll be released alongside the update when it's finished.

**Comment by spartacus04** [comment]
HHi, i said that it would be released alongside the latest update, but of it's necessity i can release It alone.
