### ISSUE TITLE
[Bug]: I cant connect to my Server

### ISSUE THREAD

**Issue by PinkJojoKun** [spartacus04/jext-reborn#374]
### Describe the bug

Hi Hi,
I just tried to setup jext reborn and had some issues cause I cant connect my server to the webui, first it asks me for a password (I didnt setup any password) and after I setup a password it still doesnt work

- yes I tried to put everything in manually and still it didnt work

TypeError: Failed to fetch
    at window.fetch (https://spartacus04.github.io/jext-reborn/_app/immutable/chunks/entry.CNiPD0BG.js:1:1667)
    at gu (https://spartacus04.github.io/jext-reborn/_app/immutable/chunks/extensions.CCJcIzRw.js:19:30137)
    at async https://spartacus04.github.io/jext-reborn/_app/immutable/nodes/3.CweCb8PN.js:3830:31418

### Steps to reproduce

start the server, run the command /jext webui config (ingame) and click on the link

### Expected behaviour

I dont know would be great to have a video tutorial or similair

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Closed due to #399
