### ISSUE TITLE
[BUG] Jukebox wont start up

### ISSUE THREAD

**Issue by AshiroKun** [spartacus04/jext-reborn#38]
**Describe the bug**
I think after the latest update that fixed the language bug, it does not load the plugin anymore once you add some music discs in?

**To Reproduce**
If I am honest I do not know how to reproduce it.

I would say start by turning the language from auto to custom and then try add some custom music and it will not load.

**Logs**
[pastebin](https://pastebin.com/qsjxjvsw)

**Enviroment (please complete the following information):**
 - Server type: PurpurMC
 - Version: 1.19

**Comment by spartacus04** [comment]
I noticed from the log that the version you are running is 0.6.6b. The bug was actually fixed in 0.6.7b.

Try updating the plugin and the bug should be fixed.
If it's still not working please open another issue
