### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by famh3** [spartacus04/jext-reborn#387]
### Describe the bug

Ok, I've been trying to use the pluggin on my geysermc aternos server but I am really confused with the WebUI bc it's asking me for a pasword and I don't know where to find that password or how to genrate it. And my server console is giving me this text: 

[14:56:19 INFO]: [JEXT] resource-pack.zip not found, please provide it in the plugin directory
[14:56:19 INFO]: [JEXT] SHA1 is required for resource pack downloads!

If someone can help me I would really apreciate it.

### Steps to reproduce

IDK what to do

### Expected behaviour

????

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
The default password is empty. Just click the submit button and it'll work
