### ISSUE TITLE
[BUG] Console spam

### ISSUE THREAD

**Issue by AshiroKun** [spartacus04/jext-reborn#39]
**Describe the bug**
From the new updated version: 0.6.9B, the silent mode works in game but in console it skills does blank messages.

**Proof**
[https://i.imgur.com/vvpX2mF.png](url)

**Enviroment (please complete the following information):**
 - Server type: PurpurMC
 - Version 1.19.2

**Comment by spartacus04** [comment]
Thanks for the bug report, I probably overlooked that. I'll fix it tomorrow

**Comment by spartacus04** [comment]
Fixed in latest version. Sorry for all the bugs in the recent releases, i developed the new updates in an enviroment where I couldn't test the plugin
