### ISSUE TITLE
[Bug]: Problems With Connect

### ISSUE THREAD

**Issue by desharish** [spartacus04/jext-reborn#398]
### Describe the bug

can't connect to my server with web server

### Steps to reproduce

1. Start server 2. jext webui

### Expected behaviour

Just how fix is

### Logs

TypeError: Failed to fetch
    at window.fetch (https://spartacus04.github.io/jext-reborn/_app/immutable/chunks/entry.ByhH81-5.js:1:1667)
    at gu (https://spartacus04.github.io/jext-reborn/_app/immutable/chunks/extensions.CCJcIzRw.js:19:30137)
    at async https://spartacus04.github.io/jext-reborn/_app/immutable/nodes/3.DwEwXPgz.js:3807:31424

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Closed due to #399
