### ISSUE TITLE
Add the ability to change the text in the plugin!

### ISSUE THREAD

**Issue by rmr4k** [spartacus04/jext-reborn#4]
The plugin is awesome! Thanks for porting it to the new version!

- Please add the ability to change the text: **"Now playing: (disk name)".** 
 
 **I really need this!**

**Comment by rmr4k** [comment]
Oh, thank you so much! I really appreciate you adding this improvement! But, I found another problem. Either I didn't notice/didn't find it, but there doesn't seem to be a reload command to reload all plugin configurations. Is this the case?

**Comment by spartacus04** [comment]
When i ported the plugin to 1.19 I there wasn't any reload command.
I'll probably add it in the future, it's not really difficoult to add it.

Thanks for the suggestion.
