### ISSUE TITLE
[Bug]: "an unexpected error occurred trying to execute that command" 

### ISSUE THREAD

**Issue by Squish4030** [spartacus04/jext-reborn#400]
### Describe the bug

Every time I try to use any of the plugin's commands, I get the message "an unexpected error occurred trying to execute that command". I have looked at tutorials on how to set it up, the webpage, and I've tried looking up the error. Even after all of this, I have not found anyone else who has had this issue. I'm playing on 1.20.6 and have protocol lib downloaded. When hovering over the error, it says the plugin is disabled, but I am unable to find a way to enable it.

### Steps to reproduce

1.) Download plugin and Protocol lib.
2.) restart server and log in
3.) try to use command. 
4.) "an unexpected error occurred trying to execute that command"

### Expected behaviour

I expect the command to run as it is supposed to

### Server Version

1.20.5

### Server Type

Paper

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by jack1888x** [comment]
have you find a solution?
