### ISSUE TITLE
[BUG] JukeLooper Integration

### ISSUE THREAD

**Issue by USBCharger** [spartacus04/jext-reborn#42]
When I try to use this plugin in conjunction with the JukeLooper plugin, (chest on top of jukebox, music discs in chest) the songs do not play, although I see my action bar say now playing song such and such (says disc 11 for a split second before saying the correct song, assume that is intentional due to the nature of the setup)

For context, putting the disc in the jukebox manually **does** work for me, and no errors show up in console.

**Enviroment (please complete the following information):**
 - Server type: Paper (git-Paper-215)
 - Version 1.19.2
 - Doubt this matters, but this is a Minehut server. Minehut can be annoying/weird about a few things, though I doubt it should matter here, but I thought I'd mention it.

**Additional context**
Contacted the JukeLooper developer on their Discord, and something they said that you might find to be helpful was this:

"That's because extra music disc plugins manually have to run code to play the sound to the player, which is only done when the player interacts directly with the jukebox since redstone jukeboxes are not a vanilla feature, it's not taking into consideration..." (Hopefully this was helpful lol)

**Comment by spartacus04** [comment]
Thanks for the bug report.

Currently I am busy with school, but after the exam season is over I can add the integration.

**Comment by USBCharger** [comment]
Alrighty, thank you! :)

**Comment by spartacus04** [comment]
Hi, Unfortunately I coulnd't resolve things on my end, so I made a PR to the jukelooper plugin adding the compatibility. You can monitor the status of the pr [here](https://gitlab.com/ranull/minecraft/jukelooper/-/merge_requests/2).

I'll keep this issue open until the pr is merged

**Comment by USBCharger** [comment]
Oki, thank you!

**Comment by spartacus04** [comment]
The PR has been merged, in the next jukelooper release there should be support for the plugin

**Comment by USBCharger** [comment]
Ayyy, nice, ty for your assistance :D

**Comment by spartacus04** [comment]
No problem
