### ISSUE TITLE
[Bug]: Asking for password even when i have not set one

### ISSUE THREAD

**Issue by JJ0236** [spartacus04/jext-reborn#433]
### Describe the bug

When i try to login to the configuration link its asking me for a JEXT server password even though i have never set one and this is the first time ive tried to use this plugin. Any help would be appreciated. Thanks

### Steps to reproduce

n/a

### Expected behaviour

whatever is supposed to happen when i open the web ui for the first time

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by choonoo** [comment]
how do you fix this
