### ISSUE TITLE
[Bug]: cant connect to the ui at all

### ISSUE THREAD

**Issue by JJ0236** [spartacus04/jext-reborn#434]
### Describe the bug

it wont let me connect using the app at all

### Steps to reproduce

type in login information and hit connect

### Expected behaviour

for it to connect and let me upload music

### Logs

TypeError: Failed to fetch     at window.fetch (http://tauri.localhost/_app/immutable/chunks/entry.CB_U4yY7.js:1:1667)     at rd (http://tauri.localhost/_app/immutable/chunks/extensions.CDut8-VP.js:19:30205)

### Server Version

1.20

### Server Type

Spigot

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Closed due to #399
