### ISSUE TITLE
[BUG] When using custom textures it changes the disc 11 texture

### ISSUE THREAD

**Issue by ImmortalBeastYT** [spartacus04/jext-reborn#49]
**Describe the bug**
I've uploaded custom textures for the discs and it changes disc 11 to the same texture as the disc with custom model data 0

**To Reproduce**
I guess just make a disc with custom textures

**Expected behavior**
Disc 11 should retain it's original texture

**Logs**
N/A

**Enviroment (please complete the following information):**
 - Server type: Paper
 - Version 1.19.2

**Additional context**
![image](https://user-images.githubusercontent.com/68069437/209240777-61ddcc52-e205-42ec-8efe-f1905b58f945.png)

**Comment by spartacus04** [comment]
Thanks for the bug report.

I just finished fixing the bug, it should be working as expected now
