### ISSUE TITLE
[BUG] Creepers do not drop custom discs

### ISSUE THREAD

**Issue by AryanOvalekar** [spartacus04/jext-reborn#51]
**Describe the bug**
When a skeleton kills a creeper, the custom discs are not dropped despite having creeper drops enabled in discs.json. The disc and discgive commands produce the working discs correctly as it is supposed to.

**To Reproduce**
1. Start a paper server on 1.19.3 with jext reborn and protocollib.
2. Make a skeleton kill a creeper (I did this over 100+ times with a disc library of 20+)
3. No custom disc ever drops

**Expected behavior**
At least once a creeper should drop one of the custom discs

**Logs**
No errors occur and the server loads up as normal

**Enviroment (please complete the following information):**
 - Tested on 1.19.2 and 1.192
 - Tested with both Paper and Purpur
 - 
**Additional context**
jext and its dependencies were the only plugins. The server was started from scratch in a linux server.

**Comment by spartacus04** [comment]
Hi, Thanks for the bug report,
Right now I can't fix It because I won't have access to a computer for the next few days.
Still, i'll try to fix It as soon as possible

**Comment by spartacus04** [comment]
Fixed in latest release
