### ISSUE TITLE
How the get the discs in game?

### ISSUE THREAD

**Issue by EzePauer** [spartacus04/jext-reborn#6]
Hey! Hope you're having a great day. We could set the plugin and the resource pack is loaded correctly, but so far, i couldn't get the discs inside the game. 

Thank you!

**Comment by spartacus04** [comment]
You can use the /disc command or they are dropped by creepers

**Comment by EzePauer** [comment]
Im sorry, after i wrote the issue i found the command.
But sadly, we couldn't get it to work. I'm uploading the error we get. 

When you type /disc or /discgive, you don't see the disc list in game.
And in the console we get "plugin is dsabled
![WhatsApp Image 2022-07-18 at 4 02 25 PM (1)](https://user-images.githubusercontent.com/73572916/179589230-849cda80-0ec2-4b88-96db-a3abe31394a8.jpeg)
![WhatsApp Image 2022-07-18 at 4 02 25 PM](https://user-images.githubusercontent.com/73572916/179589229-976cfcf8-09db-4ec9-ac47-8ab4f0d3f64d.jpeg)
"

**Comment by spartacus04** [comment]
Did you put the discs.json file in the plugin data folder?
The plugin auto disables itself when It cant find It.

**Comment by Capysussa** [comment]
i have the same problem
![server](https://user-images.githubusercontent.com/111569437/185593831-b51e82f0-f7eb-4e86-a258-a3c61609405b.JPG)

**Comment by spartacus04** [comment]
Fixed in latest release
