### ISSUE TITLE
[BUG] Disc Without Lore Has Blank Line

### ISSUE THREAD

**Issue by NutNutty64** [spartacus04/jext-reborn#61]
**Describe the bug**
Any disc created with a blank lore field will still have a big gap in the item tooltip where the lore should be

**To Reproduce**
1. create a disc
2. leave the lore field as "" or a blank box on the generator
3. gap appears

**Expected behavior**
no gap

**Logs**
No Log

**Enviroment (please complete the following information):**
 - Server type: Purpur
 - Version: 1.19.3

**Comment by spartacus04** [comment]
I just tested this out and if you set the lore field as [] then no blank lines should appear, it is probably a generator bug, I'll fix it right now

**Comment by spartacus04** [comment]
Fixed in the generator, to fix the bug in your config just replace: `lores: [""]` with `lores: []`
