### ISSUE TITLE
[BUG] No sound played

### ISSUE THREAD

**Issue by WaxenSs** [spartacus04/jext-reborn#64]
**Describe the bug**
When I put a custom disc in the jukebox, the sound is not played.

**Informations**
- Configuration done with your tool (very cool by the way)
- Texture pack installed in the server via Dropbox = no sound from customs disks
- Texture pack installed not installed in the server + installed in the client itself = no sound of the customs disks
- Disabling stereo sound = no sound from customs discs

**Enviroment (please complete the following information):**
 - Server type: Paper 1.19.3-381
 - Plugin version : 1.0.2

Do you have an idea? I followed the wiki to the letter but nothing helps :(
Shouldn't the discs exceed a certain time? My discs usually last a maximum of 4 minutes, no more

Thanks !!

**Comment by spartacus04** [comment]
Thanks for the bug report. Could you sensi me the resource pack and the discs.json file?

**Comment by WaxenSs** [comment]
[biomediscs.zip](https://github.com/spartacus04/jext-reborn/files/10510080/biomediscs.zip)

```[
  {
    "title": "revenge",
    "author": "CaptainSpaklez",
    "duration": 219,
    "disc-namespace": "music_disc.revengecaptainspaklezzero",
    "model-data": 1,
    "creeper-drop": false,
    "lores": [
      "&eLégendaire",
      "",
      "&7&o19 août 2011"
    ],
    "loot-tables": [],
    "fragment-loot-tables": [
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/simple_dungeon",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/woodland_mansion",
      "chests/abandoned_mineshaft"
    ]
  },
  {
    "title": "fallen kingdom ",
    "author": "CaptainSpaklez",
    "duration": 253,
    "disc-namespace": "music_disc.fallenkingdomcaptainspaklezone",
    "model-data": 2,
    "creeper-drop": false,
    "lores": [
      "&eLégendaire",
      "",
      "&7&o1 avr. 2012"
    ],
    "loot-tables": [],
    "fragment-loot-tables": [
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/simple_dungeon",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/woodland_mansion",
      "chests/abandoned_mineshaft"
    ]
  }
]```

fast :D

**Comment by spartacus04** [comment]
I just looked at the files you sent. I noticed that the audio files had some kind of thumbnail in them that prevented them from being played into minecraft. The generator will now remove that thumbnail automatically, you just need to import and re generate the pack in the tool.

Also, I looked at the lores in the disc and I noticed that you were trying to add colors to the discs. Just letting you know, you need the § symbol to do that, no the & symbol.
