### ISSUE TITLE
[BUG] Infinite loading of the tool online

### ISSUE THREAD

**Issue by WaxenSs** [spartacus04/jext-reborn#65]
**Describe the bug**
The problem seems to come from the number of disks I want to add.
When I want to create 14 disks via the online tool, it makes me infinitely loaded (I waited 3 hours in total before giving up)

**To Reproduce**

1. Create a disks (More than 10) with several options (for example as below) per disk.
<img width="1504" alt="CleanShot 2023-01-26 at 18 40 23@2x" src="https://user-images.githubusercontent.com/37812331/214909146-1fd52763-d7f0-4c98-9f99-e5bf1fa316a4.png">
<img width="882" alt="CleanShot 2023-01-26 at 18 41 03@2x" src="https://user-images.githubusercontent.com/37812331/214909248-90ef4385-915e-4cfd-bb3b-765c6c3a1a85.png">
2. Click on "generate"

**Expected behavior**
For information: The tool does not seem to work on the Safari browser, unlike Firefox, which works very well with it!

**Enviroment:**
Server type: Paper 1.19.3-381
Plugin version : 1.0.2

Thanks :)

**Comment by spartacus04** [comment]
I personally tested the generatore with chrome only. I'll try to find what's happening with the website performance on safari

**Comment by spartacus04** [comment]
Oh ok, that changes everything. It must be a general performance issue then

**Comment by WaxenSs** [comment]
Do you think you can fix this or I have to do everything by hand little by little by little?

**Comment by spartacus04** [comment]
Could you do me a favour, I can't seem to recreate the bug, could you press ctrl+shift+i, enter the console and check if the generator throws any error while generating the discs?

**Comment by spartacus04** [comment]
Ok, I might have figured out the issue

**Comment by WaxenSs** [comment]
I can send it to you tomorrow if it's not too late

**Comment by spartacus04** [comment]
Yeah that could be helpful too, thanks a lot

**Comment by spartacus04** [comment]
I just pushed some optimizations to the website, maybe tomorrow try to check if the bug was fixed

**Comment by WaxenSs** [comment]
I’ll also try on my side tomorrow (currently it’s night at home), I’ll keep you informed

**Comment by WaxenSs** [comment]
The problem seems to be solved, I can’t do it anymore!

**Comment by spartacus04** [comment]
Ok then, thanks for the help!
