### ISSUE TITLE
[BUG] Plugin not working/discgive giving fragments

### ISSUE THREAD

**Issue by nuttapillar** [spartacus04/jext-reborn#66]
**Describe the bug**
The latest version of JEXT won't enable on my server.
It has this error in the log:

<html>
<body>

[03:15:53] [Server thread/INFO]: [JEXT] music disc format is old, you can update it by importing and re-exporting the resource pack in the generator
--
310 | [03:15:53] [Server thread/INFO]: [https://spartacus04.github.io/jext-reborn/]
311 | [03:15:53] [Server thread/WARN]: me.spartacus04.jext.dependencies.jext-reborn.gson.JsonSyntaxException: me.spartacus04.jext.dependencies.jext-reborn.gson.stream.MalformedJsonException: Expected name at line 167 column 4 path $[12].loot-tables
312 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.dependencies.jext-reborn.gson.Gson.fromJson(Gson.java:1241)
313 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.dependencies.jext-reborn.gson.Gson.fromJson(Gson.java:1137)
314 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.dependencies.jext-reborn.gson.Gson.fromJson(Gson.java:1047)
315 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.dependencies.jext-reborn.gson.Gson.fromJson(Gson.java:1014)
316 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.config.ConfigManager$Companion.deserialize(ConfigManager.kt:30)
317 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.config.ConfigManager$Companion.load(ConfigManager.kt:50)
318 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.Jext.load(Jext.kt:36)
319 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.Jext.onEnable(Jext.kt:16)
320 | [03:15:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
321 | [03:15:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372)
322 | [03:15:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550)
323 | [03:15:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624)
324 | [03:15:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538)
325 | [03:15:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640)
326 | [03:15:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439)
327 | [03:15:53] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:338)
328 | [03:15:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
329 | [03:15:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
330 | [03:15:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
331 | [03:15:53] [Server thread/WARN]: Caused by: me.spartacus04.jext.dependencies.jext-reborn.gson.stream.MalformedJsonException: Expected name at line 167 column 4 path $[12].loot-tables
332 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.dependencies.jext-reborn.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
333 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.dependencies.jext-reborn.gson.stream.JsonReader.doPeek(JsonReader.java:514)
334 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.dependencies.jext-reborn.gson.stream.JsonReader.hasNext(JsonReader.java:422)
335 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.dependencies.jext-reborn.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:387)
336 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.dependencies.jext-reborn.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
337 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.dependencies.jext-reborn.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
338 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.dependencies.jext-reborn.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
339 | [03:15:53] [Server thread/WARN]: 	at JEXT-Reborn_1.0.2.jar//me.spartacus04.jext.dependencies.jext-reborn.gson.Gson.fromJson(Gson.java:1227)
340 | [03:15:53] [Server thread/WARN]: 	... 18 more
341 | [03:15:53] [Server thread/INFO]: [JukeboxExtendedReborn] Disabling JukeboxExtendedReborn v1.0.2

</body>
</html>

**To Reproduce**
install latest JEXt on purpur 1.19.3

**Expected behavior**
the plugin to load.

**Logs**
[If applicable, upload the error logs (please use something like [pastebin](https://pastebin.com/)).](https://mclo.gs/3q4w2SM)

**Enviroment (please complete the following information):**
 - Server type: [Purpur]
 - Version [1.19.3]

**Additional context**

**Comment by spartacus04** [comment]
Did you update the plugin from previous versions? if so, could you upload your discs.json file?

**Comment by nuttapillar** [comment]
Yeah, I think I was using the latest Main release, and I have now tried going to the latest devbuild. I just replaced the jar file and rebooted the server. 
[discs.txt](https://github.com/spartacus04/jext-reborn/files/10556686/discs.txt)

**Comment by spartacus04** [comment]
I'm not able to recreate the issue, I tried using your config and discs.json, same server type and version and the error isn't being thrown. Does this happen every time you run the server or did it happen just once?

**Comment by spartacus04** [comment]
I can't figure out why it's not working. Your error says that the discs.json file has an error in it, but the one you sent me doesn't have any. I was only able to recreate the error by manually placing a comma where the your logs showed the error happened.

Have you tried importing and re-exporting the resource pack in the generator? That should also update the disc file.

**Comment by spartacus04** [comment]
Did you manage to fix it?

**Comment by nuttapillar** [comment]
Not yet, sorry. I'm away. But when I get home, I'll try recreating the pack using your tool.

**Comment by spartacus04** [comment]
Hey, sorry to bother you again, did you manage to fix this?

**Comment by nuttapillar** [comment]
partially. The plugin starts, and I can run the commands, however the custom disks cannot be heard ingame, so still an issue with the pack, I think. I even used the latest version of the tool to generate a fresh pack with the songs, which I then added to my existing server resource pack. My other custom sounds still work, so the pack isnt entirely broken.

**Comment by spartacus04** [comment]
If you are using another resource pack with custom sounds you should manuallly merge the sounds.json file. The generator website can't do that automatically right now, but if you do that the plugin should work

**Comment by nuttapillar** [comment]
Well that's what I've done. I copied the text from the Json from this disks
pack, and pasted it into my other resource pack, making sure the formatting
is correct, and validated the Json. It has worked in the past at one point,
so I'm not sure what I've done wrong.

**Comment by spartacus04** [comment]
Hi, sorry if I haven't responded back in the last weeks I was really busy with school stuff. If possible could you send the sounds.json file in the resource pack?

**Comment by nuttapillar** [comment]
Hi, I have attached sounds.json

**Comment by nuttapillar** [comment]
https://pastebin.com/yMDYNCzm

**Comment by spartacus04** [comment]
Could you also send a copy of the resource pack, if it's not a problem?

**Comment by nuttapillar** [comment]
Here is the pack link: https\://www.dropbox.com/s/m3n9fplbt0l9rhx/MDU12.zip?dl\=1

**Comment by spartacus04** [comment]
I just took a look at the pack and there were some problems probably because of some generator updates: some audio files are not compatible with the spigot format, and some discs have the config a bit messed up. I think you should try to make a new resource pack with the generator, not importing it, but creating a new one and trying to use the new merge feature on the website. Please let me know if that works

**Comment by nuttapillar** [comment]
Thanks, I will try that. But I have many other custom sounds in my pack, so I will still try to merge them with it.

**Comment by nuttapillar** [comment]
Ok, I can now hear the music when I play a disc, so that's good! However there is one annoying thing. When I use the /discgive command, I get fragments instead. so I have to run it 9 times and craft them into a disc just to get a usable disc.

**Comment by nuttapillar** [comment]
Also, I got the custom music playing, and then teleported a player to me, and they couldn't hear it. Theyonly heard it once i stopped and started it again. But it could be an issue related to Jukelooper plugin instead, I'm just not sure. Not a big deal though.
Another thing; Is it possible yet to get these custom disks into a Bedrock resource pack, so they can hear it too?

**Comment by spartacus04** [comment]
Ok, glad to hear that you got it working the discgive command should give you discs, not fragments. I may have switched discgive with fragmentgive when making the command.

Players out of range of the jukebox cannot hear sounds that are played outside the internal minecraft range so I can't actually fix that.

About bedrock support I discovered that geysermc has a custom item system to replace custom model data, so I can try to add support to it

**Comment by spartacus04** [comment]
Ok i've fixed the discgive issue

**Comment by spartacus04** [comment]
I'll create a new issue for the bedrock support as this issue has many too many topics.
