### ISSUE TITLE
[BUG] The original sound and music of No. 11 record are played at the same time

### ISSUE THREAD

**Issue by Busyfox123** [spartacus04/jext-reborn#67]
JukeLooper plugin will only play record 11
1.19.2

**Comment by spartacus04** [comment]
Does the plugin output any error or warning? Have you added the resource pack or the discs.json file?

**Comment by spartacus04** [comment]
Did you manage to solve this? If not could you please reply to this issue so that I can help you solve it?

**Comment by Uncroww** [comment]
Yeah I got the same problem, when I put one of the custom discs of the server, I can hear both disc number 11 and the custom disc.

**Comment by spartacus04** [comment]
Perhaps you can help me then, @Busyfox123 seems to be inactive. Are you using any other plugins?

**Comment by spartacus04** [comment]
Just a few questions:
Which minecraft version are you running?
Which server software are you running?
And what protocollib version are you using?

**Comment by Uncroww** [comment]
I'm running Minecraft 1.19.4 on Fabric with some quality of life mods, but my friends on 1.19.4 Vanilla have the same problem.
Our server is on 1.19.4 with Spigot.
I assume I'm using ProtocolLib 4.8.0 (The latest version).

**Comment by spartacus04** [comment]
Protocollib 4.8.0 used with versions from 1.8 to 1.18. You should update it to 5.0. On the spigot page they can redirect you to the download. 1.19 brought a lot of breaking changes for protocollib and I think that this could be the reason

**Comment by spartacus04** [comment]
If that doesn't work could you let me know?

**Comment by Uncroww** [comment]
Oh okay thanks, I did not knew that there was a 5.0 version, I just installed it. I'll let you know if the issue persists :)

**Comment by Uncroww** [comment]
Okay so I'm back with some bad news, it still persists

**Comment by spartacus04** [comment]
Hi, I was able to fix the bug in [7841ee3](https://github.com/spartacus04/jext-reborn/commit/7841ee38a32d3e2f53b51c5dd94f7907aed5f68a), it should be implemented in the next update
