### ISSUE TITLE
GUI is DELETING dics!

### ISSUE THREAD

**Issue by DevinVan** [spartacus04/jext-reborn#70]
### Describe the bug

Ok, some really annoying ones I found were these 2 please fix them soon! 1. When using the GUI menu clicking with a disc on another one inside of the menu deletes the one being clicked on  2. While playing a disc if you pick up another in the menu and place it back in and then stop the music it deletes the one you picked up. happens with all disks custom or not.

### Steps to reproduce

Problem # 1
1. Have multiple discs inside GUI menu
2. Pick up/Left-click on a disc
3. click on another disk with the other disc
4. A disc should disappear 

Problem # 2
1. Have multiple discs inside GUI menu
2. Right-click to start playing a disc
3. Pick up/Left-click on a different disc 
5. Place disc back into GUI menu 
6. Right-click on the playing disc
7. A disc should disappear

### Expected behaviour

A disc should not disappear from the GUI

### Server Version

1.19.2

### Server Type

Paper

### Java Version

1.19.2 on a lunar client

### Discs.json

```json
{
    "title": "",
    "author": "Tenebre Rosso Sangue,01 Tenebre Rosso Sangue",
    "duration": 234,
    "disc-namespace": "music_disc.tenebrerossosanguezeroonetenebrerossosanguezero",
    "model-data": 1,
    "creeper-drop": true,
    "lores": [
      "PANOPTICON"
    ],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "Death Odyssey",
    "author": "ULTRAKILL,IMPERFECT HATRED,08 Death Odyssey.m4a",
    "duration": 314,
    "disc-namespace": "music_disc.deathodysseyultrakillimperfecthatredzeroeightdeathodysseymfouraone",
    "model-data": 2,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "Castle Vein",
    "author": "ULTRAKILL,INFINITE HYPERDEATH,09 Castle Vein",
    "duration": 341,
    "disc-namespace": "music_disc.castleveinultrakillinfinitehyperdeathzeroninecastleveintwo",
    "model-data": 3,
    "creeper-drop": true,
    "lores": [
      "This is the lore of the disc",
      "",
      "You can have multiple lines",
      "",
      "If you don't want any lores you can leave this empty"
    ],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "The Fire Is Gone",
    "author": "ULTRAKILL,INFINITE HYPERDEATH,23 The Fire Is Gone (for Music Box)",
    "duration": 171,
    "disc-namespace": "music_disc.thefireisgoneultrakillinfinitehyperdeathtwothreethefireisgoneformusicboxthree",
    "model-data": 4,
    "creeper-drop": true,
    "lores": [
      "This is the lore of the disc",
      "",
      "You can have multiple lines",
      "",
      "If you don't want any lores you can leave this empty"
    ],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "The Cyber Grind",
    "author": "ULTRAKILL,INFINITE HYPERDEATH,22 The Cyber Grind",
    "duration": 271,
    "disc-namespace": "music_disc.thecybergrindultrakillinfinitehyperdeathtwotwothecybergrindfour",
    "model-data": 5,
    "creeper-drop": true,
    "lores": [
      "This is the lore of the disc",
      "",
      "You can have multiple lines",
      "",
      "If you don't want any lores you can leave this empty"
    ],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "The Death of God's Will",
    "author": "ULTRAKILL,IMPERFECT HATRED,14 The Death of God's Will (incl.,Horns of Insurrection,).m4a",
    "duration": 312,
    "disc-namespace": "music_disc.thedeathofgodswillultrakillimperfecthatredonefourthedeathofgodswillinclhornsofinsurrectionmfourafive",
    "model-data": 6,
    "creeper-drop": true,
    "lores": [
      "This is the lore of the disc",
      "",
      "You can have multiple lines",
      "",
      "If you don't want any lores you can leave this empty"
    ],
    "loot-tables": [],
    "fragment-loot-tables": []
  }
]
```

### Resource pack

https://www.dropbox.com/s/bk6on6gtlvxbngr/hearinfire.zip?dl=0

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by spartacus04** [comment]
I'm trying to replicate the bugs but I can't seem to get it to work. Are you using the latest plugin version?

**Comment by spartacus04** [comment]
Did you manage to solve this? If not could you please reply to this issue so that I can help you solve it?

**Comment by DevinVan** [comment]
> I'm trying to replicate the bugs but I can't seem to get it to work. Are you using the latest plugin version?

yes I was using 1.0.2 at that time and I haven't retried in a minute but I expect it to be the same let me try now (sorry for not getting back sooner)

**Comment by DevinVan** [comment]
> 

using the 1.0.2 update yes its still there

**Comment by spartacus04** [comment]
Have you tried using 1.0.3?

**Comment by DevinVan** [comment]
> 

just did same result

**Comment by spartacus04** [comment]
Are you using any other plugins?

**Comment by DevinVan** [comment]
> Are you using any other plugins?

I'm using a small amount but kinda big ones they are

DualWield, Essentials, Farmer, Geyser-Spigot, Gsit, HeadHunter, JukeboxExtentionReborn, LuckPerms, Multiverse, ProLib, ReFrame, RHLeafDecay, sleep-most, Vault, ViaBackwards, ViaRewind, ViaVersion, and world-edit all on a 1.19.2 paper server using lunar client
