### ISSUE TITLE
[Bug]: the built-in tool doesn't generate the resources

### ISSUE THREAD

**Issue by jarmas97** [spartacus04/jext-reborn#73]
### Describe the bug

After accidentally uploading an MP3 file instead of OGG (yesterday - 17.02.2023) the tool doesn't generate anything. It keeps loading forever.

### Steps to reproduce

upload ogg file and try to generate ->https://spartacus04.github.io/jext-reborn/

### Expected behaviour

generating the resources

### Server Version

1.19.3

### Server Type

Spigot

### Java Version

17

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by spartacus04** [comment]
Thanks for the bug report, I think the website ran into an error while generating the discs.

If possible, could you try again while the browser debug console on?
That way if the website throws an error you can report it back to me, and I'll try to fix it

**Comment by jarmas97** [comment]
Okay, the console doesn't print any errors
![image](https://user-images.githubusercontent.com/75165450/219852830-0919ac9d-4db3-49ea-9540-8893f2ba8093.png)

**Comment by jarmas97** [comment]
Sorry, there is one thing... when nothing generates i refreshed the page and now the console shows Error:
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.

**Comment by spartacus04** [comment]
That error is not related to the generation process.

Could you send the mp3 file if that's not a problem?

**Comment by jarmas97** [comment]
Yes, I'm sending it right now

**Comment by jarmas97** [comment]
Now console says: Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by jarmas97** [comment]
But I've just downloaded the ZIP file

**Comment by jarmas97** [comment]
It works for OGG file also. I just had to wait very long to get the generated zip file. You can close the issue if You want
