### ISSUE TITLE
[FEATURE REQUEST]: Control the amount of discs spawned in monuments.

### ISSUE THREAD

**Issue by ovi-ivo** [spartacus04/jext-reborn#76]
### Is your feature request related to a problem? Please describe.

I want to put more discs to be on the server and also make them spawn in structures, but I don't want for example a chest inside a mineshaft to have like 6 discs.

### Describe the solution you'd like.

If you could please allow us to change the amount of discs spawned at each monuments and put it maybe in the config file or change that with in-game commands or anything we can work with.

### Additional context

Thank you very much for all your work on this plugin, and also the built-in tool wich is very easy to work with.
You're awesome!

**Comment by spartacus04** [comment]
Yeah I could add that easily, also Thanks for the compliments and for playing the plugin!

**Comment by ovi-ivo** [comment]
Thank you!

**Comment by spartacus04** [comment]
Added in [fc48ed4](https://github.com/spartacus04/jext-reborn/commit/fc48ed4554c46f718cf5f5e22a79b5380b50a575), it will be released when the 1.19.4 plugin update is fully finished.
