### ISSUE TITLE
[Bug]: Creeper mob drops not working?

### ISSUE THREAD

**Issue by Valadrix** [spartacus04/jext-reborn#79]
### Describe the bug

Hi it seems that the creeper mob drops dont work? Ive spawned loads in and tried but have only received default minecraft discs.

On the site Im making sure the creeper head is set to on (green) not sure whats happening?

json seems to say true as well

### Steps to reproduce

kill creeper nothing drops

### Expected behaviour

Should drop a custom disc every now and again

### Server Version

1.19.3

### Server Type

Spigot

### Java Version

1.19.4

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by Valadrix** [comment]
I think its the 1.19.4 update, it works on previous verison

**Comment by spartacus04** [comment]
Thanks for the bug report, right now I can't fix this because the protocollib maven server is down, but as soon as it's back online I'll update the plugin to 1.19.4

**Comment by spartacus04** [comment]
Hi, just fixed it in [02b7122](https://github.com/spartacus04/jext-reborn/commit/02b7122254e40938430241b68f834f1f61a6ca84), it's going to be published after the plugin is fully upgraded to 1.19.4
