### ISSUE TITLE
[FEATURE REQUEST]: Bedrock Edition support

### ISSUE THREAD

**Issue by spartacus04** [spartacus04/jext-reborn#88]
### Describe the solution you'd like.

Implement a geysermc integration to support bedrock edition

### Additional context

Related to #66 and #9

### Progress

- [ ] Plugin updates
    - [ ] Custom items
    - [ ] Custom music
- [ ] Upgrade generator to generate bedrock resourcepack

**Comment by VasysMS** [comment]
I was able to implement the functionality of music discs in GeyserMC using custom mappings within GeyserMC itself and the sound_definitions.json file in the resource pack for the Bedrock version.

**Comment by spartacus04** [comment]
Hi, did you manage to get the custom music working? I've never worked with bedrock resorce packs and I don't really know what i'm doing wrong.

**Comment by Vasysik** [comment]
Sorry for such a long delay, I have an example of how I implemented Bedrock Edition support for JEXT.

[jext_geysermc.zip](https://github.com/spartacus04/jext-reborn/files/13806317/jext_geysermc.zip)

There are 4 files in the archive:
1) jPackM0.1.zip - resource pack for Java Edition players
2) bPackM0.1.mcpack - resource pack for Bedrock Edition players
3) custom_mappings - the folder that needs to be placed in the GeyserMS plugin folder
4) disks.json - a file that needs to be placed in the Jext Reborn plugin folder
