### ISSUE TITLE
[FEATURE REQUEST] server side music

### ISSUE THREAD

**Issue by zaldhyx77** [spartacus04/jext-reborn#9]
my server is running geysermc and i think its hard to create a resource pack compatible with bedrock unless you can give a guide? or just add server side music feature. thanks

**Comment by spartacus04** [comment]
I don't think server side music is really possible without a resource pack, I'll look into it.

As for geysermc support, I think that geyser adds an option to add a resource pack for bedrock users.
For the moment you can use [this](https://rtm516.github.io/ConvertJavaTextureToBedrock/) tool to convert a resource pack made with the guides I made into a bedrock compatible one.

**Comment by zaldhyx77** [comment]
Thanks for your reply. i managed to create my own bedrock compatible resource pack but its only replaced  the original disc. Now i will look for a way to make jext compatible with bedrock too

**Comment by spartacus04** [comment]
Hi, i did a bit of research on how bedrock texture packs work, and unfortunately, there is no way to add more music discs without overriding the existing ones, so this plugin isn't compatible with neither bedrock nor geyser. I'll close the issue for now. If Microsoft modifies how bedrock resource packs are handled, maybe i could add this feature in the future.
