### ISSUE TITLE
[Bug]: JEXT using 37% of server thread according to Spark.

### ISSUE THREAD

**Issue by nuttapillar** [spartacus04/jext-reborn#90]
### Describe the bug

My server has been lagging badly, so I did a Spark summary, and I can see that JEXT is using 37% of the server thread. The next laggiest plugin is only 4.2%.

Server: Purpur 1.19.3
JEXT: 1.0.2

### Steps to reproduce

I'm not sure how to reproduce.
it just randomly started happening.

### Expected behaviour

Expected behaviour is much less lag.

### Server Version

1.19.3

### Server Type

Purpur

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by nuttapillar** [comment]
Spark Report: https://imgur.com/a/R1wkYWq

**Comment by spartacus04** [comment]
Thanks for the bug report, that issue has been resolved in the 1.0.3 version of the plugin. I advise updating to the latest version [here](https://github.com/spartacus04/jext-reborn/releases/tag/1.1.1).

If the issue still persists please reopen the issue.

**Comment by nuttapillar** [comment]
Still seems to be lagging, on 1.1.1. https://imgur.com/a/CWlLy41

**Comment by spartacus04** [comment]
Could you share the spark profile link?

**Comment by nuttapillar** [comment]
https://spark.lucko.me/MobcO5kBWu

**Comment by spartacus04** [comment]
I tried to recreate the issue on my end and couldn't replicate it. Was there something in particular that triggered the lagspike? I can see that it happends when breaking the jukebox but it's not working on my end

**Comment by nuttapillar** [comment]
It seems to be somehwat random. it's laggy for a while, then runs fine for a while, then goes back to laggy again. I'm not sure what exactly is happening at the moment the lag starts/stops.

**Comment by nuttapillar** [comment]
I've done a server reboot, and the lag is gone for now. But at some point, it will return. What should I be looking out for at the time of the lag starting?

**Comment by spartacus04** [comment]
The stack says that it's happening when a jukebox is destroyed, more specifically when it's closing the guis of players who are interacting with the jukebox

**Comment by nuttapillar** [comment]
I was just pressing the button on the jukebox, inserting and removing disks, and no lag was starting. But which GUI are you talking about? I don't have any jukebox gui. the closest I get is the chest above it that is used by Jukelooper.

**Comment by nuttapillar** [comment]
The lag seems to have come back now, but it was somewhat gradual, so im not sure exactly which action did it.

**Comment by spartacus04** [comment]
The plugin has an option to enable a jukebox gui which overrides the vanilla behaviour but since you are using jukelooper you probably aren't using it. I'll test if the server lags with jukelooper on my end. (BTW not sure if you read my comment in the spigot discussion, I'll probably lend an hand to ranull and update Jukelooper to 1.19.4, I'll also add better integration with JEXT)

**Comment by nuttapillar** [comment]
Yeah I saw your reply, and gave it a heart react. Thank you.

**Comment by spartacus04** [comment]
Could you perhaps try with this version?
[JEXT-Reborn_1.1.1_fix.zip](https://github.com/spartacus04/jext-reborn/files/11241736/JEXT-Reborn_1.1.1_fix.zip)

**Comment by nuttapillar** [comment]
I tried the new version. And tonight i joined my server and saw that it was lagging. I did a spark profile, which had been running about 12 hours since the new version was applied. In the spark profile (https://spark.lucko.me/r5hz8HWdlj) JEXT looked fine. The lag started alternating off and on again though, so I did another profile a few minutes later, and now it's showing JEXT as using 39% (https://spark.lucko.me/m1BZhrQxjk) So I'm super confused now.

**Comment by nuttapillar** [comment]
I have recently updated my server to 1.19.4, and in doing so, discovered that I nolonger need jukelooper anyway, as the jukeboxes play from storage above.
Should I try adding JEXT back in to see if updating everything has fixed the issue?

**Comment by spartacus04** [comment]
Perhaps you should wait a bit. I've asked around the spigot forums about this issue and basically I am doing something wrong with the handling of the jukebox gui. I am currently rewriting the system to fix this and while doing so I'll probably fix this performance issue too. I can't give you an exact ETA of when I'll finish this as I'm kind of busy this week, but probably in a few days the issue will be fixed

**Comment by spartacus04** [comment]
[JEXT-Reborn_1.1.2.zip](https://github.com/spartacus04/jext-reborn/files/11273335/JEXT-Reborn_1.1.2.zip)
Could you try with this build now? Apparently I'm not really good at timings because I've finished pretty quickly.

**Comment by nuttapillar** [comment]
Thanks, I've added it. I'll have a look at how it's going after my server reboot later.

**Comment by nuttapillar** [comment]
I have gone back onto my server after the reboot, and with your given JEXT applied, the TPS is terrible again, sitting on 9TPS  with only 8 players on.

**Comment by nuttapillar** [comment]
Ugh, im getting some severe server lag even without this plugin now. I think something else is messing up, and making it hard for me to pinpoint.

**Comment by nuttapillar** [comment]
After further testing, at least for now, the issue was at least partially something else. (NPCs having hundreds of armor stands inside them), So this latest version does seem to be working fine. though its possible the previous one was too, and I didn't realise. I'm very sorry if so.

**Comment by nuttapillar** [comment]
Now im really confused. i got rid of the excessive entities, whilst keeping JEXT, and the lag is bad. but its not showing in Spark as JEXt using high server resources. I Suspect it might be NPC Destinations, so I guess I'll try removing that now and keep JEXT, and see what happens.

**Comment by nuttapillar** [comment]
I did a whole bunch more trial and error swapping out things. And I'm pretty much convinced the main problem, was actually a datapack! It seems to be fine and not laggy now, with JEXt installed. But I'll report back if the lag does return.

**Comment by spartacus04** [comment]
Ok, glad it got resolved. Also don't worry about the plugin fix while trying to fix this problem I also improved the readability of the code and now it's much easier to work with.
