### ISSUE TITLE
[Bug]: Named custom records come out of jukebox renamed as Record - 11

### ISSUE THREAD

**Issue by BoeGitHub** [spartacus04/jext-reborn#92]
### Describe the bug

Whenever a named custom record is put into a jukebox and removed the name reverts to Record - 11

### Steps to reproduce

1. Rename custom record
2. Insert renamed custom record into jukebox
3. Remove renamed custom record from jukebox

### Expected behaviour

Expected behavior is that the custom record keeps its name when being inserted and removed from the jukebox.

### Server Version

1.19.4

### Server Type

Paper

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by spartacus04** [comment]
Hi thanks for the bug report, I just fixed this in [18d6d67](https://github.com/spartacus04/jext-reborn/commit/18d6d67cfc3c09a000ced42fc1a293f1323df5d1). I will release it alongside some other bug fixes when they are ready
