### ISSUE TITLE
[FEATURE REQUEST]: Editor for colored & formatted lore text on the built in tool?

### ISSUE THREAD

**Issue by 5H08** [spartacus04/jext-reborn#95]
### Is your feature request related to a problem? Please describe.

It sucks that we don't have a way to change the lore text to something not purple.

### Describe the solution you'd like.

It can be something like the editor of https://www.gamergeeks.net/apps/minecraft/give-command-generator in the "advanced options" menu

**Comment by spartacus04** [comment]
Yeah that could be really useful.
As of now you can add colors by using the minecraft color syntax like this: §c for red or §6 for gold

I'll probably add such an editor in the future

**Comment by spartacus04** [comment]
Hello, thanks for submitting this feature request, I've just published a new update which adds this.
