### ISSUE TITLE
[FEATURE REQUEST]: worldguard integration

### ISSUE THREAD

**Issue by WataLaker37821** [spartacus04/jext-reborn#99]
### Is your feature request related to a problem? Please describe.

Hi, can you add integration with worldguard?  

### Describe the solution you'd like.

Protect jukeboxes with guis in regions from being opened by other players who are non members/owners

**Comment by WataLaker37821** [comment]
still fresh, not stale

**Comment by spartacus04** [comment]
Hello, i've added this in [2fc663](https://github.com/spartacus04/jext-reborn/commit/2fc6639999611f4d3911abb5b8e06f2190e52702), it should be released in the next update
